
#ifndef _EQP_OPCODES_ROF_HPP_
#define _EQP_OPCODES_ROF_HPP_

#include "define.hpp"
#include "opcodes_canonical.hpp"
#include "opcode_translate.hpp"

namespace ReignOfFear
{
    enum Op : uint16_t
    {
        SendLoginInfo = 0x11b6,
        ApproveWorld = 0x7e47,
        LogServer = 0x19ab,
        SendCharInfo = 0x06a2,
        ExpansionInfo = 0x711a,
        GuildsList = 0x2d38,
        EnterWorld = 0x57c3,
        PostEnterWorld = 0x0c3d,
        SendMaxCharacters = 0x5349,
        SendMembership = 0x03b2,
        SendMembershipDetails = 0x0b1f,
        CharacterCreateRequest = 0x006b,
        CharacterCreate = 0x0afc,
        DeleteCharacter = 0x0ab4,
        RandomNameGenerator = 0x4453,
        ApproveName = 0x213a,
        MOTD = 0x1ae3,
        SetChatServer = 0x2a81,
        SetChatServer2 = 0x4099,
        ZoneServerInfo = 0x49d9,
        WorldComplete = 0x12d4,
        WorldUnknown001 = 0x6be3,
        FloatListThing = 0x7a19,
        ZoneUnavail = 0x6281,
        WorldClientReady = 0x43b0,
        AckPacket = 0x47a6,
        ZoneEntry = 0x1665,
        ReqNewZone = 0x3dec,
        NewZone = 0x7fff,
        ZoneSpawns = 0x0980,
        PlayerProfile = 0x46bb,
        TimeOfDay = 0x3be2,
        LevelUpdate = 0x7ce0,
        Stamina = 0x1949,
        RequestClientZoneChange = 0x647a,
        ZoneChange = 0x1eb4,
        SpawnAppearance = 0x7360,
        ChangeSize = 0x355c,
        TributeUpdate = 0x2691,
        TributeTimer = 0x3294,
        SendTributes = 0x0a1c,
        SendGuildTributes = 0x1781,
        TributeInfo = 0x5dd2,
        Weather = 0x0bd7,
        ReqClientSpawn = 0x5a4f,
        SpawnDoor = 0x7b6c,
        GroundSpawn = 0x4286,
        SendZonepoints = 0x7922,
        BlockedBuffs = 0x5a71,
        RemoveBlockedBuffs = 0x78ba,
        ClearBlockedBuffs = 0x5d3c,
        WorldObjectsSent = 0x7fa8,
        SendExpZonein = 0x25ab,
        SendAATable = 0x7791,
        ClearAA = 0x422e,
        ClearLeadershipAbilities = 0xb978,
        RespondAA = 0x379d,
        UpdateAA = 0x504f,
        SendAAStats = 0x3d1c,
        AAExpUpdate = 0x25c5,
        ExpUpdate = 0x47e3,
        HPUpdate = 0x07b8,
        ManaChange = 0x1e3b,
        TGB = 0x10a6,
        SpecialMesg = 0x362c,
        GuildMemberList = 0x4053,
        GuildMOTD = 0x0561,
        CharInventory = 0x786e,
        WearChange = 0x1ad3,
        ClientUpdate = 0x455d,
        ClientReady = 0x3f83,
        SetServerFilter = 0x5b27,
        GetGuildMOTD = 0x7ba3,
        GetGuildMOTDReply = 0x42a2,
        GuildMemberUpdate = 0x0048,
        GuildInvite = 0x5f8e,
        GuildRemove = 0x296d,
        GuildPeace = 0x17eb,
        SetGuildMOTD = 0x44d0,
        GuildList = 0x2d38,
        GuildWar = 0x395a,
        GuildLeader = 0x7c6f,
        GuildDelete = 0x241b,
        GuildInviteAccept = 0x78a5,
        GuildDemote = 0x3100,
        GuildPromote = 0x2945,
        GuildPublicNote = 0x3c2c,
        GuildManageBanker = 0x389c,
        GuildBank = 0x2ab0,
        SetGuildRank = 0x3599,
        GuildUpdateURLAndChannel = 0x7851,
        GuildStatus = 0x25a5,
        GuildCreate = 0xd2d1,
        GMServers = 0x2612,
        GMBecomeNPC = 0x5201,
        GMZoneRequest = 0x69e5,
        GMZoneRequest2 = 0x65d6,
        GMGoto = 0x0345,
        GMSearchCorpse = 0x5bed,
        GMHideMe = 0x4c65,
        GMDelCorpse = 0x6034,
        GMApproval = 0x0e37,
        GMToggle = 0x1276,
        GMSummon = 0x0655,
        GMEmoteZone = 0x1b39,
        GMEmoteWorld = 0x1f8c,
        GMFind = 0x6160,
        GMKick = 0x5646,
        GMKill = 0x507e,
        GMNameChange = 0x3077,
        GMLastName = 0x4dd7,
        InspectRequest = 0x23f1,
        InspectAnswer = 0x5794,
        InspectMessageUpdate = 0x3064,
        BeginCast = 0x17ff,
        ColoredText = 0x41cb,
        ConsentResponse = 0x183d,
        MemorizeSpell = 0x2fac,
        SwapSpell = 0x4736,
        CastSpell = 0x1cb5,
        Consider = 0x4d8d,
        FormattedMessage = 0x6afe,
        SimpleMessage = 0x02a5,
        Buff = 0x08ed,
        Illusion = 0x6c43,
        MoneyOnCorpse = 0x1837,
        RandomReply = 0x6525,
        DenyResponse = 0x344a,
        SkillUpdate = 0x52c6,
        GMTrainSkillConfirm = 0x35cc,
        RandomReq = 0x59db,
        Death = 0x3a65,
        GMTraining = 0x6e8f,
        GMEndTraining = 0x7ffe,
        GMTrainSkill = 0x444c,
        Animation = 0x5e0c,
        Begging = 0x54ac,
        Consent = 0x400e,
        ConsentDeny = 0x34c1,
        AutoFire = 0x314e,
        PetCommands = 0x0093,
        PetHoTT = 0x0df4,
        DeleteSpell = 0x305c,
        Surname = 0x1a87,
        ClearSurname = 0x17b6,
        FaceChange = 0x5b06,
        SenseHeading = 0x46c8,
        Action = 0x0ea7,
        ConsiderCorpse = 0x06c5,
        HideCorpse = 0x3c4b,
        CorpseDrag = 0x0be7,
        CorpseDrop = 0xdf77,
        Bug = 0x0c07,
        Feedback = 0x45ca,
        Report = 0x6d94,
        Damage = 0x5428,
        ChannelMessage = 0x33bc,
        Assist = 0x4cd1,
        AssistGroup = 0x63df,
        MoveCoin = 0x765a,
        ZonePlayerToBind = 0x7f99,
        KeyRing = 0x04ba,
        WhoAllRequest = 0x78eb,
        WhoAllResponse = 0x3393,
        FriendsWho = 0x3dac,
        ConfirmDelete = 0x78e0,
        Logout = 0x64bd,
        Rewind = 0x5521,
        Hide = 0x2da1,
        Jump = 0x1d47,
        Camp = 0x41cd,
        Emote = 0x37fd,
        SetRunMode = 0x2ce6,
        BankerChange = 0x4e20,
        TargetMouse = 0x0e25,
        MobHealth = 0x218d,
        TargetHoTT = 0x3af5,
        XTargetResponse = 0x7f64,
        XTargetRequest = 0x6753,
        XTargetAutoAddHaters = 0x5f51,
        TargetBuffs = 0x1c71,
        BuffCreate = 0x71f5,
        BuffRemoveRequest = 0x7efd,
        DeleteSpawn = 0x3b06,
        AutoAttack = 0x0d14,
        AutoAttack2 = 0x3912,
        Consume = 0x4692,
        MoveItem = 0x62a2,
        DeleteItem = 0x3eb5,
        DeleteCharge = 0x2d5b,
        ItemPacket = 0x5e0e,
        ItemLinkResponse = 0x2fdb,
        ItemLinkClick = 0x0353,
        ItemPreview = 0x05cf,
        NewSpawn = 0x3f5b,
        Track = 0x7d43,
        TrackTarget = 0x4c42,
        TrackUnknown = 0x2395,
        ClickDoor = 0x7cc0,
        MoveDoor = 0x5611,
        RemoveAllDoors = 0x39c9,
        EnvDamage = 0x52e9,
        BoardBoat = 0x2731,
        Forage = 0x416d,
        LeaveBoat = 0x6cc1,
        ControlBoat = 0x4aa0,
        SafeFallSuccess = 0x6d27,
        RezzComplete = 0x3297,
        RezzRequest = 0x521b,
        RezzAnswer = 0x004e,
        Shielding = 0x17d9,
        RequestDuel = 0x1ea9,
        MobRename = 0x5040,
        AugmentItem = 0x1627,
        WeaponEquip1 = 0x35c3,
        PlayerStateAdd = 0x012f,
        PlayerStateRemove = 0x1076,
        ApplyPoison = 0x1499,
        Save = 0x2e6f,
        TestBuff = 0x046e,
        CustomTitles = 0x471a,
        Split = 0x269e,
        LoadSpellSet = 0x38b4,
        Bandolier = 0x2b6f,
        PotionBelt = 0x2d1b,
        DuelResponse = 0x0dee,
        DuelResponse2 = 0x5e04,
        SaveOnZoneReq = 0x36b1,
        ReadBook = 0x383c,
        Dye = 0x62d8,
        InterruptCast = 0x7470,
        AAAction = 0x719a,
        LeadershipExpToggle = 0x3ea6,
        LeadershipExpUpdate = 0x6922,
        PurchaseLeadershipAA = 0x1962,
        UpdateLeadershipAA = 0x56aa,
        MarkNPC = 0x1a6c,
        MarkRaidNPC = 0x2d9f,
        ClearNPCMarks = 0x0d2d,
        ClearRaidNPCMarks = 0x433a,
        DelegateAbility = 0x7820,
        SetGroupTarget = 0x118a,
        Charm = 0x7118,
        Stun = 0x53c0,
        SendFindableNPCs = 0x34c3,
        FindPersonRequest = 0x2f3b,
        FindPersonReply = 0x44f7,
        Sound = 0x3cec,
        PetBuffWindow = 0x7197,
        LevelAppearance = 0x7c4d,
        Translocate = 0x6f01,
        Sacrifice = 0x76ab,
        PopupResponse = 0x2fa1,
        OnLevelMessage = 0x09cd,
        AugmentInfo = 0x7812,
        Petition = 0x2885,
        SomeItemPacketMaybe = 0x11a0,
        PVPStats = 0x3034,
        PVPLeaderBoardRequest = 0x1bce,
        PVPLeaderBoardReply = 0x3e78,
        PVPLeaderBoardDetailsRequest = 0x46f4,
        PVPLeaderBoardDetailsReply = 0x6a60,
        RestState = 0x3ad5,
        RespawnWindow = 0x7767,
        LDoNButton = 0x596e,
        SetStartCity = 0x7936,
        VoiceMacroIn = 0x202e,
        VoiceMacroOut = 0x3920,
        ItemViewUnknown = 0x0b64,
        VetRewardsAvaliable = 0x05d9,
        VetClaimRequest = 0xcdde,
        VetClaimReply = 0x361b,
        DisciplineUpdate = 0x2483,
        DisciplineTimer = 0x4933,
        MobUpdate = 0x6b5a,
        NPCMoveUpdate = 0x5bd9,
        CameraEffect = 0x5712,
        SpellEffect = 0x72b6,
        RemoveNimbusEffect = 0x3ba7,
        AltCurrency = 0x8fcb,
        AltCurrencyMerchantRequest = 0x7e3e,
        AltCurrencyMerchantReply = 0x0b60,
        AltCurrencyPurchase = 0x74a8,
        AltCurrencySell = 0x3167,
        AltCurrencySellSelection = 0x3c47,
        AltCurrencyReclaim = 0x46ed,
        CrystalCountUpdate = 0x5a82,
        CrystalCreate = 0x7616,
        CrystalReclaim = 0x73db,
        Untargetable = 0x7717,
        IncreaseStats = 0x0711,
        Weblink = 0x7cce,
        OpenContainer = 0x654f,
        Marquee = 0x288a,
        DzQuit = 0x5fc8,
        DzListTimers = 0x67b9,
        DzAddPlayer = 0x5ca2,
        DzRemovePlayer = 0x0dc1,
        DzSwapPlayer = 0x4995,
        DzMakeLeader = 0x17b2,
        DzPlayerList = 0x1aff,
        DzJoinExpeditionConfirm = 0x30df,
        DzJoinExpeditionReply = 0x15d4,
        DzExpeditionInfo = 0x3861,
        DzExpeditionList = 0x0b3b,
        DzMemberStatus = 0x26c2,
        DzLeaderStatus = 0x4021,
        DzExpeditionEndsWarning = 0x32eb,
        DzMemberList = 0x348f,
        DzCompass = 0x0e01,
        DzChooseZone = 0x6e5e,
        ManaUpdate = 0x6675,
        EnduranceUpdate = 0x71fb,
        MobManaUpdate = 0x48b5,
        MobEnduranceUpdate = 0x7cb5,
        MercenaryDataUpdateRequest = 0x6774,
        MercenaryDataUpdate = 0x5a7c,
        MercenaryDataRequest = 0x612e,
        MercenaryDataResponse = 0x0768,
        MercenaryHire = 0x18ba,
        MercenaryDismiss = 0x7ff4,
        MercenaryTimerRequest = 0x4326,
        MercenaryTimer = 0x6f9e,
        MercenaryUnknown1 = 0x7db4,
        MercenaryCommand = 0x7b21,
        MercenarySuspendRequest = 0x61b3,
        MercenarySuspendResponse = 0x5975,
        MercenaryUnsuspendResponse = 0x68b1,
        LootRequest = 0x43a7,
        EndLootRequest = 0x3d8c,
        LootItem = 0x515b,
        LootComplete = 0x256d,
        BazaarSearch = 0x2ad2,
        TraderDelItem = 0x63c8,
        BecomeTrader = 0x74bc,
        TraderShop = 0x0a5e,
        Trader = 0x6a6a,
        Barter = 0x6854,
        TradeRequest = 0x5f9e,
        TradeAcceptClick = 0x13db,
        TradeRequestAck = 0x6852,
        TradeCoins = 0x584d,
        FinishTrade = 0x3fbf,
        CancelTrade = 0x0234,
        TradeMoneyUpdate = 0x65f6,
        MoneyUpdate = 0x6e42,
        TradeBusy = 0x7c6d,
        FinishWindow = 0x1939,
        FinishWindow2 = 0x68df,
        ItemVerifyRequest = 0x2c0c,
        ItemVerifyReply = 0x40de,
        ShopPlayerSell = 0x6b4d,
        ShopRequest = 0x16ba,
        ShopEnd = 0x0d07,
        ShopEndConfirm = 0x1860,
        ShopPlayerBuy = 0x3bab,
        ShopDelItem = 0x509c,
        ClickObject = 0x7992,
        ClickObjectAction = 0x5507,
        ClearObject = 0x2ead,
        RecipeDetails = 0x7ad0,
        RecipesFavorite = 0x6960,
        RecipesSearch = 0x30f7,
        RecipeReply = 0x544e,
        RecipeAutoCombine = 0x46a4,
        TradeSkillCombine = 0x7447,
        OpenGuildTributeMaster = 0x107b,
        OpenTributeMaster = 0x6fed,
        SelectTribute = 0x5513,
        TributeItem = 0x105b,
        TributeMoney = 0x4b6d,
        TributeToggle = 0x1f50,
        TributePointUpdate = 0x01ec,
        LeaveAdventure = 0x18b3,
        AdventureFinish = 0x3d8b,
        AdventureInfoRequest = 0x38db,
        AdventureInfo = 0x1036,
        AdventureRequest = 0x325c,
        AdventureDetails = 0x4975,
        AdventureData = 0x729b,
        AdventureUpdate = 0x2df4,
        AdventureMerchantRequest = 0x2aa0,
        AdventureMerchantResponse = 0x5aed,
        AdventureMerchantPurchase = 0x725e,
        AdventureMerchantSell = 0x7882,
        AdventurePointsUpdate = 0x37cb,
        AdventureStatsRequest = 0x68c2,
        AdventureStatsReply = 0x62fa,
        AdventureLeaderboardRequest = 0x577a,
        AdventureLeaderboardReply = 0x2533,
        GroupDisband = 0x1ed0,
        GroupInvite = 0x1602,
        GroupFollow = 0x2789,
        GroupUpdate = 0x0ba4,
        GroupUpdateB = 0x5a07,
        GroupCancelInvite = 0x2b26,
        GroupAcknowledge = 0x5fae,
        GroupDelete = 0x33ca,
        CancelInvite = 0x2b26,
        GroupFollow2 = 0x4964,
        GroupInvite2 = 0x6e80,
        GroupDisbandYou = 0x623d,
        GroupDisbandOther = 0x74fa,
        GroupLeaderChange = 0x46fc,
        GroupRoles = 0x047c,
        GroupMakeLeader = 0x4129,
        DoGroupLeadershipAbility = 0x17d7,
        GroupLeadershipAAUpdate = 0x6567,
        GroupMentor = 0x56db,
        InspectBuffs = 0x01f3,
        LFGCommand = 0x4463,
        LFGGetMatchesRequest = 0x1373,
        LFGGetMatchesResponse = 0x31d8,
        LFPGetMatchesRequest = 0x7fd9,
        LFPGetMatchesResponse = 0x4111,
        LFPCommand = 0x6e8b,
        RaidInvite = 0x5fb2,
        RaidUpdate = 0x1bd1,
        Taunt = 0x0af6,
        CombatAbility = 0x6e4c,
        SenseTraps = 0x7462,
        PickPocket = 0x047b,
        Disarm = 0x70a9,
        Sneak = 0x62f4,
        Fishing = 0x53c2,
        InstillDoubt = 0x63a5,
        FeignDeath = 0x677d,
        Mend = 0x324f,
        LDoNOpen = 0x3567,
        TaskDescription = 0x2294,
        TaskActivity = 0x7181,
        CompletedTasks = 0x9495,
        TaskActivityComplete = 0x71cd,
        AcceptNewTask = 0x394d,
        CancelTask = 0x0c7f,
        TaskMemberList = 0x748e,
        OpenNewTasksWindow = 0x436c,
        AvaliableTask = 0x2bf8,
        TaskHistoryRequest = 0x6cf6,
        TaskHistoryReply = 0x25eb,
        NewTitlesAvailable = 0x45d1,
        RequestTitles = 0x1b5a,
        SendTitleList = 0x0d64,
        SetTitle = 0x0bfc,
        SetTitleReply = 0x7e20,
        PlayMP3 = 0x277c,
        ItemRecastDelay = 0x57ed,
        COUNT
    };

    static const OpCodeTranslation toCanonical[] = {
        { 0x11b6, CanonicalOp::SendLoginInfo },
        { 0x7e47, CanonicalOp::ApproveWorld },
        { 0x19ab, CanonicalOp::LogServer },
        { 0x06a2, CanonicalOp::SendCharInfo },
        { 0x711a, CanonicalOp::ExpansionInfo },
        { 0x2d38, CanonicalOp::GuildsList },
        { 0x57c3, CanonicalOp::EnterWorld },
        { 0x0c3d, CanonicalOp::PostEnterWorld },
        { 0x5349, CanonicalOp::SendMaxCharacters },
        { 0x03b2, CanonicalOp::SendMembership },
        { 0x0b1f, CanonicalOp::SendMembershipDetails },
        { 0x006b, CanonicalOp::CharacterCreateRequest },
        { 0x0afc, CanonicalOp::CharacterCreate },
        { 0x0ab4, CanonicalOp::DeleteCharacter },
        { 0x4453, CanonicalOp::RandomNameGenerator },
        { 0x213a, CanonicalOp::ApproveName },
        { 0x1ae3, CanonicalOp::MOTD },
        { 0x2a81, CanonicalOp::SetChatServer },
        { 0x4099, CanonicalOp::SetChatServer2 },
        { 0x49d9, CanonicalOp::ZoneServerInfo },
        { 0x12d4, CanonicalOp::WorldComplete },
        { 0x6be3, CanonicalOp::WorldUnknown001 },
        { 0x7a19, CanonicalOp::FloatListThing },
        { 0x6281, CanonicalOp::ZoneUnavail },
        { 0x43b0, CanonicalOp::WorldClientReady },
        { 0x47a6, CanonicalOp::AckPacket },
        { 0x1665, CanonicalOp::ZoneEntry },
        { 0x3dec, CanonicalOp::ReqNewZone },
        { 0x7fff, CanonicalOp::NewZone },
        { 0x0980, CanonicalOp::ZoneSpawns },
        { 0x46bb, CanonicalOp::PlayerProfile },
        { 0x3be2, CanonicalOp::TimeOfDay },
        { 0x7ce0, CanonicalOp::LevelUpdate },
        { 0x1949, CanonicalOp::Stamina },
        { 0x647a, CanonicalOp::RequestClientZoneChange },
        { 0x1eb4, CanonicalOp::ZoneChange },
        { 0x7360, CanonicalOp::SpawnAppearance },
        { 0x355c, CanonicalOp::ChangeSize },
        { 0x2691, CanonicalOp::TributeUpdate },
        { 0x3294, CanonicalOp::TributeTimer },
        { 0x0a1c, CanonicalOp::SendTributes },
        { 0x1781, CanonicalOp::SendGuildTributes },
        { 0x5dd2, CanonicalOp::TributeInfo },
        { 0x0bd7, CanonicalOp::Weather },
        { 0x5a4f, CanonicalOp::ReqClientSpawn },
        { 0x7b6c, CanonicalOp::SpawnDoor },
        { 0x4286, CanonicalOp::GroundSpawn },
        { 0x7922, CanonicalOp::SendZonepoints },
        { 0x5a71, CanonicalOp::BlockedBuffs },
        { 0x78ba, CanonicalOp::RemoveBlockedBuffs },
        { 0x5d3c, CanonicalOp::ClearBlockedBuffs },
        { 0x7fa8, CanonicalOp::WorldObjectsSent },
        { 0x25ab, CanonicalOp::SendExpZonein },
        { 0x7791, CanonicalOp::SendAATable },
        { 0x422e, CanonicalOp::ClearAA },
        { 0xb978, CanonicalOp::ClearLeadershipAbilities },
        { 0x379d, CanonicalOp::RespondAA },
        { 0x504f, CanonicalOp::UpdateAA },
        { 0x3d1c, CanonicalOp::SendAAStats },
        { 0x25c5, CanonicalOp::AAExpUpdate },
        { 0x47e3, CanonicalOp::ExpUpdate },
        { 0x07b8, CanonicalOp::HPUpdate },
        { 0x1e3b, CanonicalOp::ManaChange },
        { 0x10a6, CanonicalOp::TGB },
        { 0x362c, CanonicalOp::SpecialMesg },
        { 0x4053, CanonicalOp::GuildMemberList },
        { 0x0561, CanonicalOp::GuildMOTD },
        { 0x786e, CanonicalOp::CharInventory },
        { 0x1ad3, CanonicalOp::WearChange },
        { 0x455d, CanonicalOp::ClientUpdate },
        { 0x3f83, CanonicalOp::ClientReady },
        { 0x5b27, CanonicalOp::SetServerFilter },
        { 0x7ba3, CanonicalOp::GetGuildMOTD },
        { 0x42a2, CanonicalOp::GetGuildMOTDReply },
        { 0x0048, CanonicalOp::GuildMemberUpdate },
        { 0x5f8e, CanonicalOp::GuildInvite },
        { 0x296d, CanonicalOp::GuildRemove },
        { 0x17eb, CanonicalOp::GuildPeace },
        { 0x44d0, CanonicalOp::SetGuildMOTD },
        { 0x2d38, CanonicalOp::GuildList },
        { 0x395a, CanonicalOp::GuildWar },
        { 0x7c6f, CanonicalOp::GuildLeader },
        { 0x241b, CanonicalOp::GuildDelete },
        { 0x78a5, CanonicalOp::GuildInviteAccept },
        { 0x3100, CanonicalOp::GuildDemote },
        { 0x2945, CanonicalOp::GuildPromote },
        { 0x3c2c, CanonicalOp::GuildPublicNote },
        { 0x389c, CanonicalOp::GuildManageBanker },
        { 0x2ab0, CanonicalOp::GuildBank },
        { 0x3599, CanonicalOp::SetGuildRank },
        { 0x7851, CanonicalOp::GuildUpdateURLAndChannel },
        { 0x25a5, CanonicalOp::GuildStatus },
        { 0xd2d1, CanonicalOp::GuildCreate },
        { 0x2612, CanonicalOp::GMServers },
        { 0x5201, CanonicalOp::GMBecomeNPC },
        { 0x69e5, CanonicalOp::GMZoneRequest },
        { 0x65d6, CanonicalOp::GMZoneRequest2 },
        { 0x0345, CanonicalOp::GMGoto },
        { 0x5bed, CanonicalOp::GMSearchCorpse },
        { 0x4c65, CanonicalOp::GMHideMe },
        { 0x6034, CanonicalOp::GMDelCorpse },
        { 0x0e37, CanonicalOp::GMApproval },
        { 0x1276, CanonicalOp::GMToggle },
        { 0x0655, CanonicalOp::GMSummon },
        { 0x1b39, CanonicalOp::GMEmoteZone },
        { 0x1f8c, CanonicalOp::GMEmoteWorld },
        { 0x6160, CanonicalOp::GMFind },
        { 0x5646, CanonicalOp::GMKick },
        { 0x507e, CanonicalOp::GMKill },
        { 0x3077, CanonicalOp::GMNameChange },
        { 0x4dd7, CanonicalOp::GMLastName },
        { 0x23f1, CanonicalOp::InspectRequest },
        { 0x5794, CanonicalOp::InspectAnswer },
        { 0x3064, CanonicalOp::InspectMessageUpdate },
        { 0x17ff, CanonicalOp::BeginCast },
        { 0x41cb, CanonicalOp::ColoredText },
        { 0x183d, CanonicalOp::ConsentResponse },
        { 0x2fac, CanonicalOp::MemorizeSpell },
        { 0x4736, CanonicalOp::SwapSpell },
        { 0x1cb5, CanonicalOp::CastSpell },
        { 0x4d8d, CanonicalOp::Consider },
        { 0x6afe, CanonicalOp::FormattedMessage },
        { 0x02a5, CanonicalOp::SimpleMessage },
        { 0x08ed, CanonicalOp::Buff },
        { 0x6c43, CanonicalOp::Illusion },
        { 0x1837, CanonicalOp::MoneyOnCorpse },
        { 0x6525, CanonicalOp::RandomReply },
        { 0x344a, CanonicalOp::DenyResponse },
        { 0x52c6, CanonicalOp::SkillUpdate },
        { 0x35cc, CanonicalOp::GMTrainSkillConfirm },
        { 0x59db, CanonicalOp::RandomReq },
        { 0x3a65, CanonicalOp::Death },
        { 0x6e8f, CanonicalOp::GMTraining },
        { 0x7ffe, CanonicalOp::GMEndTraining },
        { 0x444c, CanonicalOp::GMTrainSkill },
        { 0x5e0c, CanonicalOp::Animation },
        { 0x54ac, CanonicalOp::Begging },
        { 0x400e, CanonicalOp::Consent },
        { 0x34c1, CanonicalOp::ConsentDeny },
        { 0x314e, CanonicalOp::AutoFire },
        { 0x0093, CanonicalOp::PetCommands },
        { 0x0df4, CanonicalOp::PetHoTT },
        { 0x305c, CanonicalOp::DeleteSpell },
        { 0x1a87, CanonicalOp::Surname },
        { 0x17b6, CanonicalOp::ClearSurname },
        { 0x5b06, CanonicalOp::FaceChange },
        { 0x46c8, CanonicalOp::SenseHeading },
        { 0x0ea7, CanonicalOp::Action },
        { 0x06c5, CanonicalOp::ConsiderCorpse },
        { 0x3c4b, CanonicalOp::HideCorpse },
        { 0x0be7, CanonicalOp::CorpseDrag },
        { 0xdf77, CanonicalOp::CorpseDrop },
        { 0x0c07, CanonicalOp::Bug },
        { 0x45ca, CanonicalOp::Feedback },
        { 0x6d94, CanonicalOp::Report },
        { 0x5428, CanonicalOp::Damage },
        { 0x33bc, CanonicalOp::ChannelMessage },
        { 0x4cd1, CanonicalOp::Assist },
        { 0x63df, CanonicalOp::AssistGroup },
        { 0x765a, CanonicalOp::MoveCoin },
        { 0x7f99, CanonicalOp::ZonePlayerToBind },
        { 0x04ba, CanonicalOp::KeyRing },
        { 0x78eb, CanonicalOp::WhoAllRequest },
        { 0x3393, CanonicalOp::WhoAllResponse },
        { 0x3dac, CanonicalOp::FriendsWho },
        { 0x78e0, CanonicalOp::ConfirmDelete },
        { 0x64bd, CanonicalOp::Logout },
        { 0x5521, CanonicalOp::Rewind },
        { 0x2da1, CanonicalOp::Hide },
        { 0x1d47, CanonicalOp::Jump },
        { 0x41cd, CanonicalOp::Camp },
        { 0x37fd, CanonicalOp::Emote },
        { 0x2ce6, CanonicalOp::SetRunMode },
        { 0x4e20, CanonicalOp::BankerChange },
        { 0x0e25, CanonicalOp::TargetMouse },
        { 0x218d, CanonicalOp::MobHealth },
        { 0x3af5, CanonicalOp::TargetHoTT },
        { 0x7f64, CanonicalOp::XTargetResponse },
        { 0x6753, CanonicalOp::XTargetRequest },
        { 0x5f51, CanonicalOp::XTargetAutoAddHaters },
        { 0x1c71, CanonicalOp::TargetBuffs },
        { 0x71f5, CanonicalOp::BuffCreate },
        { 0x7efd, CanonicalOp::BuffRemoveRequest },
        { 0x3b06, CanonicalOp::DeleteSpawn },
        { 0x0d14, CanonicalOp::AutoAttack },
        { 0x3912, CanonicalOp::AutoAttack2 },
        { 0x4692, CanonicalOp::Consume },
        { 0x62a2, CanonicalOp::MoveItem },
        { 0x3eb5, CanonicalOp::DeleteItem },
        { 0x2d5b, CanonicalOp::DeleteCharge },
        { 0x5e0e, CanonicalOp::ItemPacket },
        { 0x2fdb, CanonicalOp::ItemLinkResponse },
        { 0x0353, CanonicalOp::ItemLinkClick },
        { 0x05cf, CanonicalOp::ItemPreview },
        { 0x3f5b, CanonicalOp::NewSpawn },
        { 0x7d43, CanonicalOp::Track },
        { 0x4c42, CanonicalOp::TrackTarget },
        { 0x2395, CanonicalOp::TrackUnknown },
        { 0x7cc0, CanonicalOp::ClickDoor },
        { 0x5611, CanonicalOp::MoveDoor },
        { 0x39c9, CanonicalOp::RemoveAllDoors },
        { 0x52e9, CanonicalOp::EnvDamage },
        { 0x2731, CanonicalOp::BoardBoat },
        { 0x416d, CanonicalOp::Forage },
        { 0x6cc1, CanonicalOp::LeaveBoat },
        { 0x4aa0, CanonicalOp::ControlBoat },
        { 0x6d27, CanonicalOp::SafeFallSuccess },
        { 0x3297, CanonicalOp::RezzComplete },
        { 0x521b, CanonicalOp::RezzRequest },
        { 0x004e, CanonicalOp::RezzAnswer },
        { 0x17d9, CanonicalOp::Shielding },
        { 0x1ea9, CanonicalOp::RequestDuel },
        { 0x5040, CanonicalOp::MobRename },
        { 0x1627, CanonicalOp::AugmentItem },
        { 0x35c3, CanonicalOp::WeaponEquip1 },
        { 0x012f, CanonicalOp::PlayerStateAdd },
        { 0x1076, CanonicalOp::PlayerStateRemove },
        { 0x1499, CanonicalOp::ApplyPoison },
        { 0x2e6f, CanonicalOp::Save },
        { 0x046e, CanonicalOp::TestBuff },
        { 0x471a, CanonicalOp::CustomTitles },
        { 0x269e, CanonicalOp::Split },
        { 0x38b4, CanonicalOp::LoadSpellSet },
        { 0x2b6f, CanonicalOp::Bandolier },
        { 0x2d1b, CanonicalOp::PotionBelt },
        { 0x0dee, CanonicalOp::DuelResponse },
        { 0x5e04, CanonicalOp::DuelResponse2 },
        { 0x36b1, CanonicalOp::SaveOnZoneReq },
        { 0x383c, CanonicalOp::ReadBook },
        { 0x62d8, CanonicalOp::Dye },
        { 0x7470, CanonicalOp::InterruptCast },
        { 0x719a, CanonicalOp::AAAction },
        { 0x3ea6, CanonicalOp::LeadershipExpToggle },
        { 0x6922, CanonicalOp::LeadershipExpUpdate },
        { 0x1962, CanonicalOp::PurchaseLeadershipAA },
        { 0x56aa, CanonicalOp::UpdateLeadershipAA },
        { 0x1a6c, CanonicalOp::MarkNPC },
        { 0x2d9f, CanonicalOp::MarkRaidNPC },
        { 0x0d2d, CanonicalOp::ClearNPCMarks },
        { 0x433a, CanonicalOp::ClearRaidNPCMarks },
        { 0x7820, CanonicalOp::DelegateAbility },
        { 0x118a, CanonicalOp::SetGroupTarget },
        { 0x7118, CanonicalOp::Charm },
        { 0x53c0, CanonicalOp::Stun },
        { 0x34c3, CanonicalOp::SendFindableNPCs },
        { 0x2f3b, CanonicalOp::FindPersonRequest },
        { 0x44f7, CanonicalOp::FindPersonReply },
        { 0x3cec, CanonicalOp::Sound },
        { 0x7197, CanonicalOp::PetBuffWindow },
        { 0x7c4d, CanonicalOp::LevelAppearance },
        { 0x6f01, CanonicalOp::Translocate },
        { 0x76ab, CanonicalOp::Sacrifice },
        { 0x2fa1, CanonicalOp::PopupResponse },
        { 0x09cd, CanonicalOp::OnLevelMessage },
        { 0x7812, CanonicalOp::AugmentInfo },
        { 0x2885, CanonicalOp::Petition },
        { 0x11a0, CanonicalOp::SomeItemPacketMaybe },
        { 0x3034, CanonicalOp::PVPStats },
        { 0x1bce, CanonicalOp::PVPLeaderBoardRequest },
        { 0x3e78, CanonicalOp::PVPLeaderBoardReply },
        { 0x46f4, CanonicalOp::PVPLeaderBoardDetailsRequest },
        { 0x6a60, CanonicalOp::PVPLeaderBoardDetailsReply },
        { 0x3ad5, CanonicalOp::RestState },
        { 0x7767, CanonicalOp::RespawnWindow },
        { 0x596e, CanonicalOp::LDoNButton },
        { 0x7936, CanonicalOp::SetStartCity },
        { 0x202e, CanonicalOp::VoiceMacroIn },
        { 0x3920, CanonicalOp::VoiceMacroOut },
        { 0x0b64, CanonicalOp::ItemViewUnknown },
        { 0x05d9, CanonicalOp::VetRewardsAvaliable },
        { 0xcdde, CanonicalOp::VetClaimRequest },
        { 0x361b, CanonicalOp::VetClaimReply },
        { 0x2483, CanonicalOp::DisciplineUpdate },
        { 0x4933, CanonicalOp::DisciplineTimer },
        { 0x6b5a, CanonicalOp::MobUpdate },
        { 0x5bd9, CanonicalOp::NPCMoveUpdate },
        { 0x5712, CanonicalOp::CameraEffect },
        { 0x72b6, CanonicalOp::SpellEffect },
        { 0x3ba7, CanonicalOp::RemoveNimbusEffect },
        { 0x8fcb, CanonicalOp::AltCurrency },
        { 0x7e3e, CanonicalOp::AltCurrencyMerchantRequest },
        { 0x0b60, CanonicalOp::AltCurrencyMerchantReply },
        { 0x74a8, CanonicalOp::AltCurrencyPurchase },
        { 0x3167, CanonicalOp::AltCurrencySell },
        { 0x3c47, CanonicalOp::AltCurrencySellSelection },
        { 0x46ed, CanonicalOp::AltCurrencyReclaim },
        { 0x5a82, CanonicalOp::CrystalCountUpdate },
        { 0x7616, CanonicalOp::CrystalCreate },
        { 0x73db, CanonicalOp::CrystalReclaim },
        { 0x7717, CanonicalOp::Untargetable },
        { 0x0711, CanonicalOp::IncreaseStats },
        { 0x7cce, CanonicalOp::Weblink },
        { 0x654f, CanonicalOp::OpenContainer },
        { 0x288a, CanonicalOp::Marquee },
        { 0x5fc8, CanonicalOp::DzQuit },
        { 0x67b9, CanonicalOp::DzListTimers },
        { 0x5ca2, CanonicalOp::DzAddPlayer },
        { 0x0dc1, CanonicalOp::DzRemovePlayer },
        { 0x4995, CanonicalOp::DzSwapPlayer },
        { 0x17b2, CanonicalOp::DzMakeLeader },
        { 0x1aff, CanonicalOp::DzPlayerList },
        { 0x30df, CanonicalOp::DzJoinExpeditionConfirm },
        { 0x15d4, CanonicalOp::DzJoinExpeditionReply },
        { 0x3861, CanonicalOp::DzExpeditionInfo },
        { 0x0b3b, CanonicalOp::DzExpeditionList },
        { 0x26c2, CanonicalOp::DzMemberStatus },
        { 0x4021, CanonicalOp::DzLeaderStatus },
        { 0x32eb, CanonicalOp::DzExpeditionEndsWarning },
        { 0x348f, CanonicalOp::DzMemberList },
        { 0x0e01, CanonicalOp::DzCompass },
        { 0x6e5e, CanonicalOp::DzChooseZone },
        { 0x6675, CanonicalOp::ManaUpdate },
        { 0x71fb, CanonicalOp::EnduranceUpdate },
        { 0x48b5, CanonicalOp::MobManaUpdate },
        { 0x7cb5, CanonicalOp::MobEnduranceUpdate },
        { 0x6774, CanonicalOp::MercenaryDataUpdateRequest },
        { 0x5a7c, CanonicalOp::MercenaryDataUpdate },
        { 0x612e, CanonicalOp::MercenaryDataRequest },
        { 0x0768, CanonicalOp::MercenaryDataResponse },
        { 0x18ba, CanonicalOp::MercenaryHire },
        { 0x7ff4, CanonicalOp::MercenaryDismiss },
        { 0x4326, CanonicalOp::MercenaryTimerRequest },
        { 0x6f9e, CanonicalOp::MercenaryTimer },
        { 0x7db4, CanonicalOp::MercenaryUnknown1 },
        { 0x7b21, CanonicalOp::MercenaryCommand },
        { 0x61b3, CanonicalOp::MercenarySuspendRequest },
        { 0x5975, CanonicalOp::MercenarySuspendResponse },
        { 0x68b1, CanonicalOp::MercenaryUnsuspendResponse },
        { 0x43a7, CanonicalOp::LootRequest },
        { 0x3d8c, CanonicalOp::EndLootRequest },
        { 0x515b, CanonicalOp::LootItem },
        { 0x256d, CanonicalOp::LootComplete },
        { 0x2ad2, CanonicalOp::BazaarSearch },
        { 0x63c8, CanonicalOp::TraderDelItem },
        { 0x74bc, CanonicalOp::BecomeTrader },
        { 0x0a5e, CanonicalOp::TraderShop },
        { 0x6a6a, CanonicalOp::Trader },
        { 0x6854, CanonicalOp::Barter },
        { 0x5f9e, CanonicalOp::TradeRequest },
        { 0x13db, CanonicalOp::TradeAcceptClick },
        { 0x6852, CanonicalOp::TradeRequestAck },
        { 0x584d, CanonicalOp::TradeCoins },
        { 0x3fbf, CanonicalOp::FinishTrade },
        { 0x0234, CanonicalOp::CancelTrade },
        { 0x65f6, CanonicalOp::TradeMoneyUpdate },
        { 0x6e42, CanonicalOp::MoneyUpdate },
        { 0x7c6d, CanonicalOp::TradeBusy },
        { 0x1939, CanonicalOp::FinishWindow },
        { 0x68df, CanonicalOp::FinishWindow2 },
        { 0x2c0c, CanonicalOp::ItemVerifyRequest },
        { 0x40de, CanonicalOp::ItemVerifyReply },
        { 0x6b4d, CanonicalOp::ShopPlayerSell },
        { 0x16ba, CanonicalOp::ShopRequest },
        { 0x0d07, CanonicalOp::ShopEnd },
        { 0x1860, CanonicalOp::ShopEndConfirm },
        { 0x3bab, CanonicalOp::ShopPlayerBuy },
        { 0x509c, CanonicalOp::ShopDelItem },
        { 0x7992, CanonicalOp::ClickObject },
        { 0x5507, CanonicalOp::ClickObjectAction },
        { 0x2ead, CanonicalOp::ClearObject },
        { 0x7ad0, CanonicalOp::RecipeDetails },
        { 0x6960, CanonicalOp::RecipesFavorite },
        { 0x30f7, CanonicalOp::RecipesSearch },
        { 0x544e, CanonicalOp::RecipeReply },
        { 0x46a4, CanonicalOp::RecipeAutoCombine },
        { 0x7447, CanonicalOp::TradeSkillCombine },
        { 0x107b, CanonicalOp::OpenGuildTributeMaster },
        { 0x6fed, CanonicalOp::OpenTributeMaster },
        { 0x5513, CanonicalOp::SelectTribute },
        { 0x105b, CanonicalOp::TributeItem },
        { 0x4b6d, CanonicalOp::TributeMoney },
        { 0x1f50, CanonicalOp::TributeToggle },
        { 0x01ec, CanonicalOp::TributePointUpdate },
        { 0x18b3, CanonicalOp::LeaveAdventure },
        { 0x3d8b, CanonicalOp::AdventureFinish },
        { 0x38db, CanonicalOp::AdventureInfoRequest },
        { 0x1036, CanonicalOp::AdventureInfo },
        { 0x325c, CanonicalOp::AdventureRequest },
        { 0x4975, CanonicalOp::AdventureDetails },
        { 0x729b, CanonicalOp::AdventureData },
        { 0x2df4, CanonicalOp::AdventureUpdate },
        { 0x2aa0, CanonicalOp::AdventureMerchantRequest },
        { 0x5aed, CanonicalOp::AdventureMerchantResponse },
        { 0x725e, CanonicalOp::AdventureMerchantPurchase },
        { 0x7882, CanonicalOp::AdventureMerchantSell },
        { 0x37cb, CanonicalOp::AdventurePointsUpdate },
        { 0x68c2, CanonicalOp::AdventureStatsRequest },
        { 0x62fa, CanonicalOp::AdventureStatsReply },
        { 0x577a, CanonicalOp::AdventureLeaderboardRequest },
        { 0x2533, CanonicalOp::AdventureLeaderboardReply },
        { 0x1ed0, CanonicalOp::GroupDisband },
        { 0x1602, CanonicalOp::GroupInvite },
        { 0x2789, CanonicalOp::GroupFollow },
        { 0x0ba4, CanonicalOp::GroupUpdate },
        { 0x5a07, CanonicalOp::GroupUpdateB },
        { 0x2b26, CanonicalOp::GroupCancelInvite },
        { 0x5fae, CanonicalOp::GroupAcknowledge },
        { 0x33ca, CanonicalOp::GroupDelete },
        { 0x2b26, CanonicalOp::CancelInvite },
        { 0x4964, CanonicalOp::GroupFollow2 },
        { 0x6e80, CanonicalOp::GroupInvite2 },
        { 0x623d, CanonicalOp::GroupDisbandYou },
        { 0x74fa, CanonicalOp::GroupDisbandOther },
        { 0x46fc, CanonicalOp::GroupLeaderChange },
        { 0x047c, CanonicalOp::GroupRoles },
        { 0x4129, CanonicalOp::GroupMakeLeader },
        { 0x17d7, CanonicalOp::DoGroupLeadershipAbility },
        { 0x6567, CanonicalOp::GroupLeadershipAAUpdate },
        { 0x56db, CanonicalOp::GroupMentor },
        { 0x01f3, CanonicalOp::InspectBuffs },
        { 0x4463, CanonicalOp::LFGCommand },
        { 0x1373, CanonicalOp::LFGGetMatchesRequest },
        { 0x31d8, CanonicalOp::LFGGetMatchesResponse },
        { 0x7fd9, CanonicalOp::LFPGetMatchesRequest },
        { 0x4111, CanonicalOp::LFPGetMatchesResponse },
        { 0x6e8b, CanonicalOp::LFPCommand },
        { 0x5fb2, CanonicalOp::RaidInvite },
        { 0x1bd1, CanonicalOp::RaidUpdate },
        { 0x0af6, CanonicalOp::Taunt },
        { 0x6e4c, CanonicalOp::CombatAbility },
        { 0x7462, CanonicalOp::SenseTraps },
        { 0x047b, CanonicalOp::PickPocket },
        { 0x70a9, CanonicalOp::Disarm },
        { 0x62f4, CanonicalOp::Sneak },
        { 0x53c2, CanonicalOp::Fishing },
        { 0x63a5, CanonicalOp::InstillDoubt },
        { 0x677d, CanonicalOp::FeignDeath },
        { 0x324f, CanonicalOp::Mend },
        { 0x3567, CanonicalOp::LDoNOpen },
        { 0x2294, CanonicalOp::TaskDescription },
        { 0x7181, CanonicalOp::TaskActivity },
        { 0x9495, CanonicalOp::CompletedTasks },
        { 0x71cd, CanonicalOp::TaskActivityComplete },
        { 0x394d, CanonicalOp::AcceptNewTask },
        { 0x0c7f, CanonicalOp::CancelTask },
        { 0x748e, CanonicalOp::TaskMemberList },
        { 0x436c, CanonicalOp::OpenNewTasksWindow },
        { 0x2bf8, CanonicalOp::AvaliableTask },
        { 0x6cf6, CanonicalOp::TaskHistoryRequest },
        { 0x25eb, CanonicalOp::TaskHistoryReply },
        { 0x45d1, CanonicalOp::NewTitlesAvailable },
        { 0x1b5a, CanonicalOp::RequestTitles },
        { 0x0d64, CanonicalOp::SendTitleList },
        { 0x0bfc, CanonicalOp::SetTitle },
        { 0x7e20, CanonicalOp::SetTitleReply },
        { 0x277c, CanonicalOp::PlayMP3 },
        { 0x57ed, CanonicalOp::ItemRecastDelay }
    };
}

#endif//_EQP_OPCODES_ROF_HPP_
