
#ifndef _EQP_OPCODES_TITANIUM_HPP_
#define _EQP_OPCODES_TITANIUM_HPP_

#include "define.hpp"
#include "opcodes_canonical.hpp"
#include "opcode_translate.hpp"

namespace Titanium
{
    enum Op : uint16_t
    {
        ApproveWorld = 0x3c25,
        LogServer = 0x0fa6,
        MOTD = 0x024d,
        SendLoginInfo = 0x4dd0,
        DeleteCharacter = 0x26c9,
        SendCharInfo = 0x4513,
        ExpansionInfo = 0x04ec,
        CharacterCreate = 0x10b2,
        RandomNameGenerator = 0x23d4,
        GuildsList = 0x6957,
        ApproveName = 0x3ea6,
        EnterWorld = 0x7cba,
        PostEnterWorld = 0x52a4,
        SetChatServer = 0x00d7,
        SetChatServer2 = 0x6536,
        ZoneServerInfo = 0x61b6,
        WorldComplete = 0x509d,
        ZoneUnavail = 0x407c,
        WorldClientReady = 0x5e99,
        CharacterStillInZone = 0x60fa,
        WorldChecksumFailure = 0x7d37,
        WorldLoginFailed = 0x8da7,
        WorldLogout = 0x7718,
        WorldLevelTooHigh = 0x583b,
        CharInacessable = 0x436a,
        ZoneEntry = 0x7213,
        AckPacket = 0x7752,
        NewZone = 0x0920,
        ReqClientSpawn = 0x0322,
        ZoneSpawns = 0x2e78,
        CharInventory = 0x5394,
        SetServerFilter = 0x6563,
        LockoutTimerInfo = 0x7f63,
        SendZonepoints = 0x3eba,
        SpawnDoor = 0x4c24,
        ReqNewZone = 0x7ac5,
        PlayerProfile = 0x75df,
        TimeOfDay = 0x1580,
        Logout = 0x61ff,
        LogoutReply = 0x3cdc,
        PreLogoutReply = 0x711e,
        LevelUpdate = 0x6d44,
        Stamina = 0x7a83,
        Petition = 0x251f,
        PetitionQue = 0x33c3,
        PetitionDelete = 0x5692,
        ZoneGuildList = 0x6957,
        GetGuildMOTD = 0x7fec,
        GetGuildMOTDReply = 0x3246,
        GuildMemberList = 0x147d,
        GuildMemberUpdate = 0x0f4d,
        GuildRemove = 0x0179,
        GuildPeace = 0x215a,
        GuildWar = 0x0c81,
        GuildLeader = 0x12b1,
        GuildDemote = 0x4eb9,
        GuildMOTD = 0x475a,
        SetGuildMOTD = 0x591c,
        GuildInvite = 0x18b7,
        GuildPublicNote = 0x17a2,
        GuildDelete = 0x6cce,
        GuildInviteAccept = 0x61d0,
        GuildManageBanker = 0x3d1e,
        GuildBank = 0xb4ab,
        SetGuildRank = 0x6966,
        LFGuild = 0x1858,
        GMServers = 0x3387,
        GMBecomeNPC = 0x7864,
        GMZoneRequest = 0x1306,
        GMSearchCorpse = 0x3c32,
        GMHideMe = 0x15b2,
        GMGoto = 0x1cee,
        GMDelCorpse = 0x0b2f,
        GMApproval = 0x0c0f,
        GMToggle = 0x7fea,
        GMZoneRequest2 = 0x244c,
        GMSummon = 0x1edc,
        GMEmoteZone = 0x39f2,
        GMEmoteWorld = 0x3383,
        GMFind = 0x5930,
        GMKick = 0x692c,
        GMTraining = 0x238f,
        GMEndTraining = 0x613d,
        GMTrainSkill = 0x11d2,
        Animation = 0x2acf,
        Stun = 0x1e51,
        MoneyUpdate = 0x267c,
        SendExpZonein = 0x0587,
        IncreaseStats = 0x5b7b,
        CrashDump = 0x7825,
        ReadBook = 0x1496,
        Dye = 0x00dd,
        Consume = 0x77d6,
        Begging = 0x13e7,
        InspectRequest = 0x775d,
        InspectAnswer = 0x2403,
        BeginCast = 0x3990,
        ColoredText = 0x0b2d,
        Consent = 0x1081,
        ConsentDeny = 0x4e8c,
        ConsentResponse = 0x6380,
        LFGCommand = 0x68ac,
        LFGGetMatchesRequest = 0x022f,
        LFGAppearance = 0x1a85,
        LFGGetMatchesResponse = 0x45d0,
        LootItem = 0x7081,
        Bug = 0x7ac2,
        BoardBoat = 0x4298,
        Save = 0x736b,
        Camp = 0x78c1,
        EndLootRequest = 0x2316,
        MemorizeSpell = 0x308e,
        SwapSpell = 0x2126,
        CastSpell = 0x304b,
        DeleteSpell = 0x4f37,
        LoadSpellSet = 0x403e,
        AutoAttack = 0x5e55,
        AutoFire = 0x6c53,
        Consider = 0x65ca,
        Emote = 0x547a,
        PetCommands = 0x10a1,
        PetBuffWindow = 0x4e31,
        SpawnAppearance = 0x7c32,
        DeleteSpawn = 0x55bc,
        FormattedMessage = 0x5a48,
        WhoAllRequest = 0x5cdd,
        WhoAllResponse = 0x757b,
        AutoAttack2 = 0x0701,
        SetRunMode = 0x4aba,
        SimpleMessage = 0x673c,
        SaveOnZoneReq = 0x1540,
        SenseHeading = 0x05ac,
        Buff = 0x6a53,
        LootComplete = 0x0a94,
        EnvDamage = 0x31b3,
        Split = 0x4848,
        Surname = 0x4668,
        ClearSurname = 0x6cdb,
        MoveItem = 0x420f,
        FaceChange = 0x0f8e,
        ItemPacket = 0x3397,
        ItemLinkResponse = 0x667c,
        ClientReady = 0x5e20,
        ZoneChange = 0x5dd8,
        ItemLinkClick = 0x53e5,
        Forage = 0x4796,
        BazaarSearch = 0x1ee9,
        NewSpawn = 0x1860,
        WearChange = 0x7441,
        Action = 0x497c,
        SpecialMesg = 0x2372,
        LeaveBoat = 0x67c9,
        Weather = 0x254d,
        LFPGetMatchesRequest = 0x35a6,
        Illusion = 0x448d,
        TargetCommand = 0x1477,
        TargetMouse = 0x6c47,
        TargetHoTT = 0x6a12,
        GMKill = 0x6980,
        MoneyOnCorpse = 0x7fe4,
        ClickDoor = 0x043b,
        MoveDoor = 0x700d,
        RemoveAllDoors = 0x77d0,
        LootRequest = 0x6f90,
        YellForHelp = 0x61ef,
        ManaChange = 0x4839,
        LFPCommand = 0x6f82,
        RandomReply = 0x6cd5,
        DenyResponse = 0x7c66,
        ConsiderCorpse = 0x773f,
        CorpseDrag = 0x50c0,
        CorpseDrop = 0x7c7c,
        ConfirmDelete = 0x3838,
        MobHealth = 0x0695,
        SkillUpdate = 0x6a93,
        RandomReq = 0x5534,
        ClientUpdate = 0x14cb,
        Report = 0x7f9d,
        GroundSpawn = 0x0f47,
        LFPGetMatchesResponse = 0x06c5,
        Jump = 0x0797,
        ExpUpdate = 0x5ecd,
        Death = 0x6160,
        BecomeCorpse = 0x4dbc,
        GMLastName = 0x23a1,
        InitialMobHealth = 0x3d2d,
        Mend = 0x14ef,
        Feedback = 0x5306,
        TGB = 0x0c11,
        InterruptCast = 0x0b97,
        Damage = 0x5c78,
        ChannelMessage = 0x1004,
        LevelAppearance = 0x358e,
        Charm = 0x12e5,
        Assist = 0x7709,
        AssistGroup = 0x5104,
        AugmentItem = 0x539b,
        DeleteItem = 0x4d81,
        DeleteCharge = 0x1c4a,
        ControlBoat = 0x2c81,
        FeignDeath = 0x7489,
        LDoNButton = 0x13c8,
        MoveCoin = 0x7657,
        ZonePlayerToBind = 0x385e,
        Rewind = 0x4cfa,
        Translocate = 0x8258,
        Sacrifice = 0x727a,
        KeyRing = 0x68c4,
        ApplyPoison = 0x0c2c,
        AugmentInfo = 0x45ff,
        SetStartCity = 0x41dc,
        SpellEffect = 0x22c5,
        CrystalReclaim = 0x7cfe,
        CrystalCreate = 0x62c3,
        Marquee = 0x1d4d,
        DzQuit = 0x486d,
        DzListTimers = 0x39aa,
        DzAddPlayer = 0x7fba,
        DzRemovePlayer = 0x540b,
        DzSwapPlayer = 0x794a,
        DzMakeLeader = 0x0ce9,
        DzPlayerList = 0xada0,
        DzJoinExpeditionConfirm = 0x3817,
        DzJoinExpeditionReply = 0x5da9,
        DzExpeditionInfo = 0x098e,
        DzMemberStatus = 0x1826,
        DzLeaderStatus = 0x7abc,
        DzExpeditionEndsWarning = 0x1c3f,
        DzExpeditionList = 0x7c12,
        DzMemberList = 0x09b6,
        DzCompass = 0x28aa,
        DzChooseZone = 0x1022,
        TraderDelItem = 0x0da9,
        BecomeTrader = 0x2844,
        TraderShop = 0x35e8,
        Trader = 0x524e,
        TraderBuy = 0x6dd8,
        Barter = 0x7460,
        TradeRequest = 0x372f,
        TradeAcceptClick = 0x0065,
        TradeRequestAck = 0x4048,
        TradeCoins = 0x34c1,
        FinishTrade = 0x6014,
        CancelTrade = 0x2dc1,
        TradeBusy = 0x6839,
        ShopPlayerSell = 0x0e13,
        ShopEnd = 0x7e03,
        ShopEndConfirm = 0x20b2,
        ShopPlayerBuy = 0x221e,
        ShopRequest = 0x45f9,
        ShopDelItem = 0x0da9,
        ClickObject = 0x3bc2,
        ClickObjectAction = 0x6937,
        ClearObject = 0x21ed,
        RecipeDetails = 0x4ea2,
        RecipesFavorite = 0x23f0,
        RecipesSearch = 0x164d,
        RecipeReply = 0x31f8,
        RecipeAutoCombine = 0x0353,
        TradeSkillCombine = 0x0b40,
        RequestDuel = 0x28e1,
        DuelResponse = 0x3bad,
        DuelResponse2 = 0x1b09,
        RezzComplete = 0x4b05,
        RezzRequest = 0x1035,
        RezzAnswer = 0x6219,
        SafeFallSuccess = 0x3b21,
        Shielding = 0x3fe6,
        TestBuff = 0x6ab0,
        Track = 0x5d11,
        TrackTarget = 0x7085,
        TrackUnknown = 0x6177,
        OpenTributeMaster = 0x512e,
        OpenTributeReply = 0x27b3,
        SelectTribute = 0x625d,
        TributeItem = 0x6f6c,
        TributeMoney = 0x27b3,
        TributeNPC = 0x7f25,
        TributeToggle = 0x2688,
        TributeTimer = 0x4665,
        TributePointUpdate = 0x6463,
        TributeUpdate = 0x5639,
        GuildTributeInfo = 0x5e3d,
        TributeInfo = 0x152d,
        SendGuildTributes = 0x5e3a,
        SendTributes = 0x067a,
        LeaveAdventure = 0x0c0d,
        AdventureFinish = 0x3906,
        AdventureInfoRequest = 0x2aaf,
        AdventureInfo = 0x1db5,
        AdventureRequest = 0x43fd,
        AdventureDetails = 0x3f26,
        AdventureData = 0x0677,
        AdventureUpdate = 0x64ac,
        AdventureMerchantRequest = 0x0950,
        AdventureMerchantResponse = 0x4416,
        AdventureMerchantPurchase = 0x413d,
        AdventureMerchantSell = 0x0097,
        AdventurePointsUpdate = 0x420a,
        AdventureStatsRequest = 0x5fc7,
        AdventureStatsReply = 0x56cd,
        AdventureLeaderboardRequest = 0x230a,
        AdventureLeaderboardReply = 0x0d0f,
        GroupDisband = 0x0e76,
        GroupInvite = 0x1b48,
        GroupFollow = 0x7bc7,
        GroupUpdate = 0x2dd6,
        GroupCancelInvite = 0x1f27,
        GroupInvite2 = 0x12d6,
        RaidJoin = 0x1f21,
        RaidInvite = 0x5891,
        RaidUpdate = 0x1f21,
        InspectBuffs = 0x4fb6,
        DisciplineUpdate = 0x7180,
        DisciplineTimer = 0x53df,
        FindPersonRequest = 0x3c41,
        FindPersonReply = 0x5711,
        Sound = 0x541e,
        MobRename = 0x0498,
        BankerChange = 0x6a5b,
        Taunt = 0x5e48,
        CombatAbility = 0x5ee8,
        SenseTraps = 0x5666,
        PickPocket = 0x2ad8,
        DisarmTraps = 0x1241,
        Disarm = 0x17d9,
        Hide = 0x4312,
        Sneak = 0x74e1,
        Fishing = 0x0b36,
        InstillDoubt = 0x389e,
        LDoNOpen = 0x083b,
        TaskActivityComplete = 0x54eb,
        CompletedTasks = 0x76a2,
        TaskDescription = 0x5ef7,
        TaskActivity = 0x682d,
        TaskMemberList = 0x722f,
        OpenNewTasksWindow = 0x5e7c,
        AcceptNewTask = 0x207f,
        TaskHistoryRequest = 0x5df4,
        TaskHistoryReply = 0x397d,
        CancelTask = 0x3ba8,
        TaskMemberInvite = 0x79b4,
        TaskMemberInviteResponse = 0x0358,
        TaskMemberChange = 0x5886,
        TaskMakeLeader = 0x1b25,
        TaskAddPlayer = 0x6bc4,
        TaskRemovePlayer = 0x37b9,
        TaskPlayerList = 0x3961,
        TaskQuit = 0x35dd,
        RequestClientZoneChange = 0x7834,
        SendAATable = 0x367d,
        UpdateAA = 0x5966,
        RespondAA = 0x3af4,
        SendAAStats = 0x5996,
        AAAction = 0x0681,
        AAExpUpdate = 0x5f58,
        PurchaseLeadershipAA = 0x17bf,
        UpdateLeadershipAA = 0x07f1,
        LeadershipExpUpdate = 0x596e,
        LeadershipExpToggle = 0x5b37,
        MarkNPC = 0x5483,
        ClearNPCMarks = 0x3ef6,
        DoGroupLeadershipAbility = 0x569e,
        DelegateAbility = 0x10f4,
        SetGroupTarget = 0x3eec,
        PlayMP3 = 0x26ab,
        FriendsWho = 0x48fe,
        MoveLogRequest = 0x7510,
        ReclaimCrystals = 0x7cfe,
        CrystalCountUpdate = 0x0ce3,
        CustomTitles = 0x2a28,
        NewTitlesAvailable = 0x4eca,
        RequestTitles = 0x5eba,
        SendTitleList = 0x3e89,
        SetTitle = 0x1f22,
        SetTitleReply = 0x5eab,
        Bandolier = 0x6f0c,
        PotionBelt = 0x0719,
        OnLevelMessage = 0x1dde,
        PopupResponse = 0x3816,
        SlashAdventure = 0x571a,
        VetRewardsAvaliable = 0x0557,
        VetClaimRequest = 0x6ba0,
        VetClaimReply = 0x407e,
        BecomePVPPrompt = 0x36b2,
        PVPStats = 0x5cc0,
        PVPLeaderBoardRequest = 0x61d2,
        PVPLeaderBoardReply = 0x1a59,
        PVPLeaderBoardDetailsRequest = 0x06a2,
        PVPLeaderBoardDetailsReply = 0x246a,
        PickLockSuccess = 0x40e7,
        WeaponEquip1 = 0x6c5e,
        PlayerStateAdd = 0x63da,
        PlayerStateRemove = 0x381d,
        VoiceMacroIn = 0x2866,
        VoiceMacroOut = 0x2ec6,
        CameraEffect = 0x0937,
        AnnoyingZoneUnknown = 0x729c,
        SomeItemPacketMaybe = 0x4033,
        QueryResponseThing = 0x1974,
        FloatListThing = 0x6a1b,
        HPUpdate = 0x3bcf,
        COUNT
    };

    static const OpCodeTranslation toCanonical[] = {
        { 0x3c25, CanonicalOp::ApproveWorld },
        { 0x0fa6, CanonicalOp::LogServer },
        { 0x024d, CanonicalOp::MOTD },
        { 0x4dd0, CanonicalOp::SendLoginInfo },
        { 0x26c9, CanonicalOp::DeleteCharacter },
        { 0x4513, CanonicalOp::SendCharInfo },
        { 0x04ec, CanonicalOp::ExpansionInfo },
        { 0x10b2, CanonicalOp::CharacterCreate },
        { 0x23d4, CanonicalOp::RandomNameGenerator },
        { 0x6957, CanonicalOp::GuildsList },
        { 0x3ea6, CanonicalOp::ApproveName },
        { 0x7cba, CanonicalOp::EnterWorld },
        { 0x52a4, CanonicalOp::PostEnterWorld },
        { 0x00d7, CanonicalOp::SetChatServer },
        { 0x6536, CanonicalOp::SetChatServer2 },
        { 0x61b6, CanonicalOp::ZoneServerInfo },
        { 0x509d, CanonicalOp::WorldComplete },
        { 0x407c, CanonicalOp::ZoneUnavail },
        { 0x5e99, CanonicalOp::WorldClientReady },
        { 0x60fa, CanonicalOp::CharacterStillInZone },
        { 0x7d37, CanonicalOp::WorldChecksumFailure },
        { 0x8da7, CanonicalOp::WorldLoginFailed },
        { 0x7718, CanonicalOp::WorldLogout },
        { 0x583b, CanonicalOp::WorldLevelTooHigh },
        { 0x436a, CanonicalOp::CharInacessable },
        { 0x7213, CanonicalOp::ZoneEntry },
        { 0x7752, CanonicalOp::AckPacket },
        { 0x0920, CanonicalOp::NewZone },
        { 0x0322, CanonicalOp::ReqClientSpawn },
        { 0x2e78, CanonicalOp::ZoneSpawns },
        { 0x5394, CanonicalOp::CharInventory },
        { 0x6563, CanonicalOp::SetServerFilter },
        { 0x7f63, CanonicalOp::LockoutTimerInfo },
        { 0x3eba, CanonicalOp::SendZonepoints },
        { 0x4c24, CanonicalOp::SpawnDoor },
        { 0x7ac5, CanonicalOp::ReqNewZone },
        { 0x75df, CanonicalOp::PlayerProfile },
        { 0x1580, CanonicalOp::TimeOfDay },
        { 0x61ff, CanonicalOp::Logout },
        { 0x3cdc, CanonicalOp::LogoutReply },
        { 0x711e, CanonicalOp::PreLogoutReply },
        { 0x6d44, CanonicalOp::LevelUpdate },
        { 0x7a83, CanonicalOp::Stamina },
        { 0x251f, CanonicalOp::Petition },
        { 0x33c3, CanonicalOp::PetitionQue },
        { 0x5692, CanonicalOp::PetitionDelete },
        { 0x6957, CanonicalOp::ZoneGuildList },
        { 0x7fec, CanonicalOp::GetGuildMOTD },
        { 0x3246, CanonicalOp::GetGuildMOTDReply },
        { 0x147d, CanonicalOp::GuildMemberList },
        { 0x0f4d, CanonicalOp::GuildMemberUpdate },
        { 0x0179, CanonicalOp::GuildRemove },
        { 0x215a, CanonicalOp::GuildPeace },
        { 0x0c81, CanonicalOp::GuildWar },
        { 0x12b1, CanonicalOp::GuildLeader },
        { 0x4eb9, CanonicalOp::GuildDemote },
        { 0x475a, CanonicalOp::GuildMOTD },
        { 0x591c, CanonicalOp::SetGuildMOTD },
        { 0x18b7, CanonicalOp::GuildInvite },
        { 0x17a2, CanonicalOp::GuildPublicNote },
        { 0x6cce, CanonicalOp::GuildDelete },
        { 0x61d0, CanonicalOp::GuildInviteAccept },
        { 0x3d1e, CanonicalOp::GuildManageBanker },
        { 0xb4ab, CanonicalOp::GuildBank },
        { 0x6966, CanonicalOp::SetGuildRank },
        { 0x1858, CanonicalOp::LFGuild },
        { 0x3387, CanonicalOp::GMServers },
        { 0x7864, CanonicalOp::GMBecomeNPC },
        { 0x1306, CanonicalOp::GMZoneRequest },
        { 0x3c32, CanonicalOp::GMSearchCorpse },
        { 0x15b2, CanonicalOp::GMHideMe },
        { 0x1cee, CanonicalOp::GMGoto },
        { 0x0b2f, CanonicalOp::GMDelCorpse },
        { 0x0c0f, CanonicalOp::GMApproval },
        { 0x7fea, CanonicalOp::GMToggle },
        { 0x244c, CanonicalOp::GMZoneRequest2 },
        { 0x1edc, CanonicalOp::GMSummon },
        { 0x39f2, CanonicalOp::GMEmoteZone },
        { 0x3383, CanonicalOp::GMEmoteWorld },
        { 0x5930, CanonicalOp::GMFind },
        { 0x692c, CanonicalOp::GMKick },
        { 0x238f, CanonicalOp::GMTraining },
        { 0x613d, CanonicalOp::GMEndTraining },
        { 0x11d2, CanonicalOp::GMTrainSkill },
        { 0x2acf, CanonicalOp::Animation },
        { 0x1e51, CanonicalOp::Stun },
        { 0x267c, CanonicalOp::MoneyUpdate },
        { 0x0587, CanonicalOp::SendExpZonein },
        { 0x5b7b, CanonicalOp::IncreaseStats },
        { 0x7825, CanonicalOp::CrashDump },
        { 0x1496, CanonicalOp::ReadBook },
        { 0x00dd, CanonicalOp::Dye },
        { 0x77d6, CanonicalOp::Consume },
        { 0x13e7, CanonicalOp::Begging },
        { 0x775d, CanonicalOp::InspectRequest },
        { 0x2403, CanonicalOp::InspectAnswer },
        { 0x3990, CanonicalOp::BeginCast },
        { 0x0b2d, CanonicalOp::ColoredText },
        { 0x1081, CanonicalOp::Consent },
        { 0x4e8c, CanonicalOp::ConsentDeny },
        { 0x6380, CanonicalOp::ConsentResponse },
        { 0x68ac, CanonicalOp::LFGCommand },
        { 0x022f, CanonicalOp::LFGGetMatchesRequest },
        { 0x1a85, CanonicalOp::LFGAppearance },
        { 0x45d0, CanonicalOp::LFGGetMatchesResponse },
        { 0x7081, CanonicalOp::LootItem },
        { 0x7ac2, CanonicalOp::Bug },
        { 0x4298, CanonicalOp::BoardBoat },
        { 0x736b, CanonicalOp::Save },
        { 0x78c1, CanonicalOp::Camp },
        { 0x2316, CanonicalOp::EndLootRequest },
        { 0x308e, CanonicalOp::MemorizeSpell },
        { 0x2126, CanonicalOp::SwapSpell },
        { 0x304b, CanonicalOp::CastSpell },
        { 0x4f37, CanonicalOp::DeleteSpell },
        { 0x403e, CanonicalOp::LoadSpellSet },
        { 0x5e55, CanonicalOp::AutoAttack },
        { 0x6c53, CanonicalOp::AutoFire },
        { 0x65ca, CanonicalOp::Consider },
        { 0x547a, CanonicalOp::Emote },
        { 0x10a1, CanonicalOp::PetCommands },
        { 0x4e31, CanonicalOp::PetBuffWindow },
        { 0x7c32, CanonicalOp::SpawnAppearance },
        { 0x55bc, CanonicalOp::DeleteSpawn },
        { 0x5a48, CanonicalOp::FormattedMessage },
        { 0x5cdd, CanonicalOp::WhoAllRequest },
        { 0x757b, CanonicalOp::WhoAllResponse },
        { 0x0701, CanonicalOp::AutoAttack2 },
        { 0x4aba, CanonicalOp::SetRunMode },
        { 0x673c, CanonicalOp::SimpleMessage },
        { 0x1540, CanonicalOp::SaveOnZoneReq },
        { 0x05ac, CanonicalOp::SenseHeading },
        { 0x6a53, CanonicalOp::Buff },
        { 0x0a94, CanonicalOp::LootComplete },
        { 0x31b3, CanonicalOp::EnvDamage },
        { 0x4848, CanonicalOp::Split },
        { 0x4668, CanonicalOp::Surname },
        { 0x6cdb, CanonicalOp::ClearSurname },
        { 0x420f, CanonicalOp::MoveItem },
        { 0x0f8e, CanonicalOp::FaceChange },
        { 0x3397, CanonicalOp::ItemPacket },
        { 0x667c, CanonicalOp::ItemLinkResponse },
        { 0x5e20, CanonicalOp::ClientReady },
        { 0x5dd8, CanonicalOp::ZoneChange },
        { 0x53e5, CanonicalOp::ItemLinkClick },
        { 0x4796, CanonicalOp::Forage },
        { 0x1ee9, CanonicalOp::BazaarSearch },
        { 0x1860, CanonicalOp::NewSpawn },
        { 0x7441, CanonicalOp::WearChange },
        { 0x497c, CanonicalOp::Action },
        { 0x2372, CanonicalOp::SpecialMesg },
        { 0x67c9, CanonicalOp::LeaveBoat },
        { 0x254d, CanonicalOp::Weather },
        { 0x35a6, CanonicalOp::LFPGetMatchesRequest },
        { 0x448d, CanonicalOp::Illusion },
        { 0x1477, CanonicalOp::TargetCommand },
        { 0x6c47, CanonicalOp::TargetMouse },
        { 0x6a12, CanonicalOp::TargetHoTT },
        { 0x6980, CanonicalOp::GMKill },
        { 0x7fe4, CanonicalOp::MoneyOnCorpse },
        { 0x043b, CanonicalOp::ClickDoor },
        { 0x700d, CanonicalOp::MoveDoor },
        { 0x77d0, CanonicalOp::RemoveAllDoors },
        { 0x6f90, CanonicalOp::LootRequest },
        { 0x61ef, CanonicalOp::YellForHelp },
        { 0x4839, CanonicalOp::ManaChange },
        { 0x6f82, CanonicalOp::LFPCommand },
        { 0x6cd5, CanonicalOp::RandomReply },
        { 0x7c66, CanonicalOp::DenyResponse },
        { 0x773f, CanonicalOp::ConsiderCorpse },
        { 0x50c0, CanonicalOp::CorpseDrag },
        { 0x7c7c, CanonicalOp::CorpseDrop },
        { 0x3838, CanonicalOp::ConfirmDelete },
        { 0x0695, CanonicalOp::MobHealth },
        { 0x6a93, CanonicalOp::SkillUpdate },
        { 0x5534, CanonicalOp::RandomReq },
        { 0x14cb, CanonicalOp::ClientUpdate },
        { 0x7f9d, CanonicalOp::Report },
        { 0x0f47, CanonicalOp::GroundSpawn },
        { 0x06c5, CanonicalOp::LFPGetMatchesResponse },
        { 0x0797, CanonicalOp::Jump },
        { 0x5ecd, CanonicalOp::ExpUpdate },
        { 0x6160, CanonicalOp::Death },
        { 0x4dbc, CanonicalOp::BecomeCorpse },
        { 0x23a1, CanonicalOp::GMLastName },
        { 0x3d2d, CanonicalOp::InitialMobHealth },
        { 0x14ef, CanonicalOp::Mend },
        { 0x5306, CanonicalOp::Feedback },
        { 0x0c11, CanonicalOp::TGB },
        { 0x0b97, CanonicalOp::InterruptCast },
        { 0x5c78, CanonicalOp::Damage },
        { 0x1004, CanonicalOp::ChannelMessage },
        { 0x358e, CanonicalOp::LevelAppearance },
        { 0x12e5, CanonicalOp::Charm },
        { 0x7709, CanonicalOp::Assist },
        { 0x5104, CanonicalOp::AssistGroup },
        { 0x539b, CanonicalOp::AugmentItem },
        { 0x4d81, CanonicalOp::DeleteItem },
        { 0x1c4a, CanonicalOp::DeleteCharge },
        { 0x2c81, CanonicalOp::ControlBoat },
        { 0x7489, CanonicalOp::FeignDeath },
        { 0x13c8, CanonicalOp::LDoNButton },
        { 0x7657, CanonicalOp::MoveCoin },
        { 0x385e, CanonicalOp::ZonePlayerToBind },
        { 0x4cfa, CanonicalOp::Rewind },
        { 0x8258, CanonicalOp::Translocate },
        { 0x727a, CanonicalOp::Sacrifice },
        { 0x68c4, CanonicalOp::KeyRing },
        { 0x0c2c, CanonicalOp::ApplyPoison },
        { 0x45ff, CanonicalOp::AugmentInfo },
        { 0x41dc, CanonicalOp::SetStartCity },
        { 0x22c5, CanonicalOp::SpellEffect },
        { 0x7cfe, CanonicalOp::CrystalReclaim },
        { 0x62c3, CanonicalOp::CrystalCreate },
        { 0x1d4d, CanonicalOp::Marquee },
        { 0x486d, CanonicalOp::DzQuit },
        { 0x39aa, CanonicalOp::DzListTimers },
        { 0x7fba, CanonicalOp::DzAddPlayer },
        { 0x540b, CanonicalOp::DzRemovePlayer },
        { 0x794a, CanonicalOp::DzSwapPlayer },
        { 0x0ce9, CanonicalOp::DzMakeLeader },
        { 0xada0, CanonicalOp::DzPlayerList },
        { 0x3817, CanonicalOp::DzJoinExpeditionConfirm },
        { 0x5da9, CanonicalOp::DzJoinExpeditionReply },
        { 0x098e, CanonicalOp::DzExpeditionInfo },
        { 0x1826, CanonicalOp::DzMemberStatus },
        { 0x7abc, CanonicalOp::DzLeaderStatus },
        { 0x1c3f, CanonicalOp::DzExpeditionEndsWarning },
        { 0x7c12, CanonicalOp::DzExpeditionList },
        { 0x09b6, CanonicalOp::DzMemberList },
        { 0x28aa, CanonicalOp::DzCompass },
        { 0x1022, CanonicalOp::DzChooseZone },
        { 0x0da9, CanonicalOp::TraderDelItem },
        { 0x2844, CanonicalOp::BecomeTrader },
        { 0x35e8, CanonicalOp::TraderShop },
        { 0x524e, CanonicalOp::Trader },
        { 0x6dd8, CanonicalOp::TraderBuy },
        { 0x7460, CanonicalOp::Barter },
        { 0x372f, CanonicalOp::TradeRequest },
        { 0x0065, CanonicalOp::TradeAcceptClick },
        { 0x4048, CanonicalOp::TradeRequestAck },
        { 0x34c1, CanonicalOp::TradeCoins },
        { 0x6014, CanonicalOp::FinishTrade },
        { 0x2dc1, CanonicalOp::CancelTrade },
        { 0x6839, CanonicalOp::TradeBusy },
        { 0x0e13, CanonicalOp::ShopPlayerSell },
        { 0x7e03, CanonicalOp::ShopEnd },
        { 0x20b2, CanonicalOp::ShopEndConfirm },
        { 0x221e, CanonicalOp::ShopPlayerBuy },
        { 0x45f9, CanonicalOp::ShopRequest },
        { 0x0da9, CanonicalOp::ShopDelItem },
        { 0x3bc2, CanonicalOp::ClickObject },
        { 0x6937, CanonicalOp::ClickObjectAction },
        { 0x21ed, CanonicalOp::ClearObject },
        { 0x4ea2, CanonicalOp::RecipeDetails },
        { 0x23f0, CanonicalOp::RecipesFavorite },
        { 0x164d, CanonicalOp::RecipesSearch },
        { 0x31f8, CanonicalOp::RecipeReply },
        { 0x0353, CanonicalOp::RecipeAutoCombine },
        { 0x0b40, CanonicalOp::TradeSkillCombine },
        { 0x28e1, CanonicalOp::RequestDuel },
        { 0x3bad, CanonicalOp::DuelResponse },
        { 0x1b09, CanonicalOp::DuelResponse2 },
        { 0x4b05, CanonicalOp::RezzComplete },
        { 0x1035, CanonicalOp::RezzRequest },
        { 0x6219, CanonicalOp::RezzAnswer },
        { 0x3b21, CanonicalOp::SafeFallSuccess },
        { 0x3fe6, CanonicalOp::Shielding },
        { 0x6ab0, CanonicalOp::TestBuff },
        { 0x5d11, CanonicalOp::Track },
        { 0x7085, CanonicalOp::TrackTarget },
        { 0x6177, CanonicalOp::TrackUnknown },
        { 0x512e, CanonicalOp::OpenTributeMaster },
        { 0x27b3, CanonicalOp::OpenTributeReply },
        { 0x625d, CanonicalOp::SelectTribute },
        { 0x6f6c, CanonicalOp::TributeItem },
        { 0x27b3, CanonicalOp::TributeMoney },
        { 0x7f25, CanonicalOp::TributeNPC },
        { 0x2688, CanonicalOp::TributeToggle },
        { 0x4665, CanonicalOp::TributeTimer },
        { 0x6463, CanonicalOp::TributePointUpdate },
        { 0x5639, CanonicalOp::TributeUpdate },
        { 0x5e3d, CanonicalOp::GuildTributeInfo },
        { 0x152d, CanonicalOp::TributeInfo },
        { 0x5e3a, CanonicalOp::SendGuildTributes },
        { 0x067a, CanonicalOp::SendTributes },
        { 0x0c0d, CanonicalOp::LeaveAdventure },
        { 0x3906, CanonicalOp::AdventureFinish },
        { 0x2aaf, CanonicalOp::AdventureInfoRequest },
        { 0x1db5, CanonicalOp::AdventureInfo },
        { 0x43fd, CanonicalOp::AdventureRequest },
        { 0x3f26, CanonicalOp::AdventureDetails },
        { 0x0677, CanonicalOp::AdventureData },
        { 0x64ac, CanonicalOp::AdventureUpdate },
        { 0x0950, CanonicalOp::AdventureMerchantRequest },
        { 0x4416, CanonicalOp::AdventureMerchantResponse },
        { 0x413d, CanonicalOp::AdventureMerchantPurchase },
        { 0x0097, CanonicalOp::AdventureMerchantSell },
        { 0x420a, CanonicalOp::AdventurePointsUpdate },
        { 0x5fc7, CanonicalOp::AdventureStatsRequest },
        { 0x56cd, CanonicalOp::AdventureStatsReply },
        { 0x230a, CanonicalOp::AdventureLeaderboardRequest },
        { 0x0d0f, CanonicalOp::AdventureLeaderboardReply },
        { 0x0e76, CanonicalOp::GroupDisband },
        { 0x1b48, CanonicalOp::GroupInvite },
        { 0x7bc7, CanonicalOp::GroupFollow },
        { 0x2dd6, CanonicalOp::GroupUpdate },
        { 0x1f27, CanonicalOp::GroupCancelInvite },
        { 0x12d6, CanonicalOp::GroupInvite2 },
        { 0x1f21, CanonicalOp::RaidJoin },
        { 0x5891, CanonicalOp::RaidInvite },
        { 0x1f21, CanonicalOp::RaidUpdate },
        { 0x4fb6, CanonicalOp::InspectBuffs },
        { 0x7180, CanonicalOp::DisciplineUpdate },
        { 0x53df, CanonicalOp::DisciplineTimer },
        { 0x3c41, CanonicalOp::FindPersonRequest },
        { 0x5711, CanonicalOp::FindPersonReply },
        { 0x541e, CanonicalOp::Sound },
        { 0x0498, CanonicalOp::MobRename },
        { 0x6a5b, CanonicalOp::BankerChange },
        { 0x5e48, CanonicalOp::Taunt },
        { 0x5ee8, CanonicalOp::CombatAbility },
        { 0x5666, CanonicalOp::SenseTraps },
        { 0x2ad8, CanonicalOp::PickPocket },
        { 0x1241, CanonicalOp::DisarmTraps },
        { 0x17d9, CanonicalOp::Disarm },
        { 0x4312, CanonicalOp::Hide },
        { 0x74e1, CanonicalOp::Sneak },
        { 0x0b36, CanonicalOp::Fishing },
        { 0x389e, CanonicalOp::InstillDoubt },
        { 0x083b, CanonicalOp::LDoNOpen },
        { 0x54eb, CanonicalOp::TaskActivityComplete },
        { 0x76a2, CanonicalOp::CompletedTasks },
        { 0x5ef7, CanonicalOp::TaskDescription },
        { 0x682d, CanonicalOp::TaskActivity },
        { 0x722f, CanonicalOp::TaskMemberList },
        { 0x5e7c, CanonicalOp::OpenNewTasksWindow },
        { 0x207f, CanonicalOp::AcceptNewTask },
        { 0x5df4, CanonicalOp::TaskHistoryRequest },
        { 0x397d, CanonicalOp::TaskHistoryReply },
        { 0x3ba8, CanonicalOp::CancelTask },
        { 0x79b4, CanonicalOp::TaskMemberInvite },
        { 0x0358, CanonicalOp::TaskMemberInviteResponse },
        { 0x5886, CanonicalOp::TaskMemberChange },
        { 0x1b25, CanonicalOp::TaskMakeLeader },
        { 0x6bc4, CanonicalOp::TaskAddPlayer },
        { 0x37b9, CanonicalOp::TaskRemovePlayer },
        { 0x3961, CanonicalOp::TaskPlayerList },
        { 0x35dd, CanonicalOp::TaskQuit },
        { 0x7834, CanonicalOp::RequestClientZoneChange },
        { 0x367d, CanonicalOp::SendAATable },
        { 0x5966, CanonicalOp::UpdateAA },
        { 0x3af4, CanonicalOp::RespondAA },
        { 0x5996, CanonicalOp::SendAAStats },
        { 0x0681, CanonicalOp::AAAction },
        { 0x5f58, CanonicalOp::AAExpUpdate },
        { 0x17bf, CanonicalOp::PurchaseLeadershipAA },
        { 0x07f1, CanonicalOp::UpdateLeadershipAA },
        { 0x596e, CanonicalOp::LeadershipExpUpdate },
        { 0x5b37, CanonicalOp::LeadershipExpToggle },
        { 0x5483, CanonicalOp::MarkNPC },
        { 0x3ef6, CanonicalOp::ClearNPCMarks },
        { 0x569e, CanonicalOp::DoGroupLeadershipAbility },
        { 0x10f4, CanonicalOp::DelegateAbility },
        { 0x3eec, CanonicalOp::SetGroupTarget },
        { 0x26ab, CanonicalOp::PlayMP3 },
        { 0x48fe, CanonicalOp::FriendsWho },
        { 0x7510, CanonicalOp::MoveLogRequest },
        { 0x7cfe, CanonicalOp::ReclaimCrystals },
        { 0x0ce3, CanonicalOp::CrystalCountUpdate },
        { 0x2a28, CanonicalOp::CustomTitles },
        { 0x4eca, CanonicalOp::NewTitlesAvailable },
        { 0x5eba, CanonicalOp::RequestTitles },
        { 0x3e89, CanonicalOp::SendTitleList },
        { 0x1f22, CanonicalOp::SetTitle },
        { 0x5eab, CanonicalOp::SetTitleReply },
        { 0x6f0c, CanonicalOp::Bandolier },
        { 0x0719, CanonicalOp::PotionBelt },
        { 0x1dde, CanonicalOp::OnLevelMessage },
        { 0x3816, CanonicalOp::PopupResponse },
        { 0x571a, CanonicalOp::SlashAdventure },
        { 0x0557, CanonicalOp::VetRewardsAvaliable },
        { 0x6ba0, CanonicalOp::VetClaimRequest },
        { 0x407e, CanonicalOp::VetClaimReply },
        { 0x36b2, CanonicalOp::BecomePVPPrompt },
        { 0x5cc0, CanonicalOp::PVPStats },
        { 0x61d2, CanonicalOp::PVPLeaderBoardRequest },
        { 0x1a59, CanonicalOp::PVPLeaderBoardReply },
        { 0x06a2, CanonicalOp::PVPLeaderBoardDetailsRequest },
        { 0x246a, CanonicalOp::PVPLeaderBoardDetailsReply },
        { 0x40e7, CanonicalOp::PickLockSuccess },
        { 0x6c5e, CanonicalOp::WeaponEquip1 },
        { 0x63da, CanonicalOp::PlayerStateAdd },
        { 0x381d, CanonicalOp::PlayerStateRemove },
        { 0x2866, CanonicalOp::VoiceMacroIn },
        { 0x2ec6, CanonicalOp::VoiceMacroOut },
        { 0x0937, CanonicalOp::CameraEffect },
        { 0x729c, CanonicalOp::AnnoyingZoneUnknown },
        { 0x4033, CanonicalOp::SomeItemPacketMaybe },
        { 0x1974, CanonicalOp::QueryResponseThing },
        { 0x6a1b, CanonicalOp::FloatListThing },
        { 0x3bcf, CanonicalOp::HPUpdate }
    };
}

#endif//_EQP_OPCODES_TITANIUM_HPP_
