
#ifndef _EQP_OPCODES_ROF2_HPP_
#define _EQP_OPCODES_ROF2_HPP_

#include "define.hpp"
#include "opcodes_canonical.hpp"
#include "opcode_translate.hpp"

namespace ReignOfFear2
{
    enum Op : uint16_t
    {
        SendLoginInfo = 0x7a09,
        ApproveWorld = 0x7499,
        LogServer = 0x7ceb,
        SendCharInfo = 0x00d2,
        ExpansionInfo = 0x590d,
        GuildsList = 0x507a,
        EnterWorld = 0x578f,
        PostEnterWorld = 0x6259,
        SendMaxCharacters = 0x5475,
        SendMembership = 0x7acc,
        SendMembershipDetails = 0x057b,
        CharacterCreateRequest = 0x6773,
        CharacterCreate = 0x6bbf,
        DeleteCharacter = 0x1808,
        RandomNameGenerator = 0x5954,
        ApproveName = 0x56a2,
        MOTD = 0x0c22,
        SetChatServer = 0x1bc5,
        SetChatServer2 = 0x7eec,
        ZoneServerInfo = 0x4c44,
        WorldComplete = 0x4493,
        WorldUnknown001 = 0x2301,
        FloatListThing = 0x46c6,
        ZoneUnavail = 0x4cb4,
        WorldClientReady = 0x23c1,
        AckPacket = 0x471d,
        ZoneEntry = 0x5089,
        ReqNewZone = 0x7887,
        NewZone = 0x1795,
        ZoneSpawns = 0x5237,
        PlayerProfile = 0x6506,
        TimeOfDay = 0x5070,
        LevelUpdate = 0x1eec,
        Stamina = 0x2a79,
        RequestClientZoneChange = 0x3fcf,
        ZoneChange = 0x2d18,
        SpawnAppearance = 0x0971,
        ChangeSize = 0x4707,
        TributeUpdate = 0x5961,
        TributeTimer = 0x073d,
        SendTributes = 0x729b,
        SendGuildTributes = 0x1877,
        TributeInfo = 0x4254,
        Weather = 0x661e,
        ReqClientSpawn = 0x35fa,
        SpawnDoor = 0x7291,
        GroundSpawn = 0x6fca,
        SendZonepoints = 0x69a4,
        BlockedBuffs = 0x3033,
        RemoveBlockedBuffs = 0x0de7,
        ClearBlockedBuffs = 0x34cb,
        WorldObjectsSent = 0x5ae2,
        SendExpZonein = 0x5f8e,
        SendAATable = 0x66b5,
        ClearAA = 0x0f50,
        ClearLeadershipAbilities = 0x6da5,
        RespondAA = 0x7a27,
        UpdateAA = 0x66f0,
        SendAAStats = 0x43c8,
        AAExpUpdate = 0x7d14,
        ExpUpdate = 0x20ed,
        HPUpdate = 0x2828,
        ManaChange = 0x5467,
        TGB = 0x0876,
        SpecialMesg = 0x0083,
        GuildMemberList = 0x12a6,
        GuildMOTD = 0x3e13,
        CharInventory = 0x5ca6,
        WearChange = 0x7994,
        ClientUpdate = 0x7dfc,
        ClientReady = 0x345d,
        SetServerFilter = 0x444d,
        GetGuildMOTD = 0x36e0,
        GetGuildMOTDReply = 0x4f1f,
        GuildMemberUpdate = 0x69b9,
        GuildInvite = 0x7099,
        GuildRemove = 0x1444,
        GuildPeace = 0x67e3,
        SetGuildMOTD = 0x0b0b,
        GuildWar = 0x1ffb,
        GuildLeader = 0x7e09,
        GuildDelete = 0x3708,
        GuildInviteAccept = 0x7053,
        GuildDemote = 0x2d4e,
        GuildPromote = 0x6a98,
        GuildPublicNote = 0x5053,
        GuildManageBanker = 0x3f35,
        GuildBank = 0x5134,
        SetGuildRank = 0x0b9c,
        GuildUpdateURLAndChannel = 0x2958,
        GuildStatus = 0x7326,
        GuildCreate = 0x76d9,
        GMServers = 0x08c1,
        GMBecomeNPC = 0x3ae1,
        GMZoneRequest = 0x62ac,
        GMZoneRequest2 = 0x7e1a,
        GMGoto = 0x7d8e,
        GMSearchCorpse = 0x357c,
        GMHideMe = 0x79c5,
        GMDelCorpse = 0x607e,
        GMApproval = 0x6db5,
        GMToggle = 0x2097,
        GMSummon = 0x486f,
        GMEmoteZone = 0x1cfd,
        GMEmoteWorld = 0x458e,
        GMFind = 0x4a8f,
        GMKick = 0x26a7,
        GMKill = 0x51d3,
        GMNameChange = 0x035f,
        GMLastName = 0x46ce,
        InspectRequest = 0x57bc,
        InspectAnswer = 0x71ac,
        InspectMessageUpdate = 0x4d25,
        BeginCast = 0x318f,
        ColoredText = 0x43af,
        ConsentResponse = 0x384a,
        MemorizeSpell = 0x217c,
        SwapSpell = 0x0efa,
        CastSpell = 0x1287,
        Consider = 0x742b,
        FormattedMessage = 0x1024,
        SimpleMessage = 0x213f,
        Buff = 0x659c,
        Illusion = 0x312a,
        MoneyOnCorpse = 0x5f44,
        RandomReply = 0x106b,
        DenyResponse = 0x2382,
        SkillUpdate = 0x004c,
        GMTrainSkillConfirm = 0x4b64,
        RandomReq = 0x7b10,
        Death = 0x6517,
        GMTraining = 0x1966,
        GMEndTraining = 0x4d6b,
        GMTrainSkill = 0x2a85,
        Animation = 0x7177,
        Begging = 0x6703,
        Consent = 0x1fd1,
        ConsentDeny = 0x7a45,
        AutoFire = 0x241e,
        PetCommands = 0x0159,
        PetHoTT = 0x794a,
        DeleteSpell = 0x3358,
        Surname = 0x0423,
        ClearSurname = 0x3fb0,
        FaceChange = 0x5578,
        SenseHeading = 0x260a,
        Action = 0x744c,
        ConsiderCorpse = 0x5204,
        HideCorpse = 0x49e1,
        CorpseDrag = 0x0904,
        CorpseDrop = 0x7037,
        Bug = 0x73f4,
        Feedback = 0x5602,
        Report = 0x6f14,
        Damage = 0x6f15,
        ChannelMessage = 0x2b2d,
        Assist = 0x4478,
        AssistGroup = 0x27f8,
        MoveCoin = 0x0bcf,
        ZonePlayerToBind = 0x08d8,
        KeyRing = 0x1219,
        WhoAllRequest = 0x674b,
        WhoAllResponse = 0x578c,
        FriendsWho = 0x3956,
        ConfirmDelete = 0x43a3,
        Logout = 0x4ac6,
        Rewind = 0x1745,
        TargetCommand = 0x58e2,
        Hide = 0x67fe,
        Jump = 0x31f4,
        Camp = 0x28ec,
        Emote = 0x373b,
        SetRunMode = 0x009f,
        BankerChange = 0x791e,
        TargetMouse = 0x075d,
        MobHealth = 0x37b1,
        TargetHoTT = 0x0272,
        TargetBuffs = 0x4f4b,
        XTargetResponse = 0x4d59,
        XTargetRequest = 0x3763,
        XTargetAutoAddHaters = 0x672f,
        BuffCreate = 0x3377,
        BuffRemoveRequest = 0x64f2,
        DeleteSpawn = 0x7280,
        AutoAttack = 0x109d,
        AutoAttack2 = 0x3526,
        Consume = 0x4b70,
        MoveItem = 0x32ee,
        DeleteItem = 0x18ad,
        DeleteCharge = 0x01b8,
        ItemPacket = 0x368e,
        ItemLinkResponse = 0x70c0,
        ItemLinkClick = 0x4cef,
        ItemPreview = 0x6b5c,
        NewSpawn = 0x6097,
        Track = 0x17e5,
        TrackTarget = 0x695e,
        TrackUnknown = 0x4577,
        ClickDoor = 0x3a8f,
        MoveDoor = 0x08e8,
        RemoveAllDoors = 0x700c,
        EnvDamage = 0x51fd,
        BoardBoat = 0x4211,
        LeaveBoat = 0x7617,
        ControlBoat = 0x0ae7,
        Forage = 0x5306,
        SafeFallSuccess = 0x2219,
        RezzComplete = 0x760d,
        RezzRequest = 0x3c21,
        RezzAnswer = 0x701c,
        Shielding = 0x52e5,
        RequestDuel = 0x3af1,
        MobRename = 0x2c57,
        AugmentItem = 0x661b,
        WeaponEquip1 = 0x34a7,
        PlayerStateAdd = 0x559a,
        PlayerStateRemove = 0x2d25,
        ApplyPoison = 0x31e6,
        Save = 0x4a39,
        TestBuff = 0x7cb8,
        CustomTitles = 0x100e,
        Split = 0x3a54,
        YellForHelp = 0x4e56,
        LoadSpellSet = 0x261d,
        Bandolier = 0x7677,
        PotionBelt = 0x1a3e,
        DuelResponse = 0x6a46,
        DuelResponse2 = 0x68d3,
        SaveOnZoneReq = 0x600d,
        ReadBook = 0x72df,
        Dye = 0x23b9,
        InterruptCast = 0x048c,
        AAAction = 0x424e,
        LeadershipExpToggle = 0x74bd,
        LeadershipExpUpdate = 0x2797,
        PurchaseLeadershipAA = 0x6c55,
        MarkNPC = 0x1fb5,
        MarkRaidNPC = 0x5a58,
        ClearNPCMarks = 0x2003,
        ClearRaidNPCMarks = 0x20d3,
        DelegateAbility = 0x4c9d,
        Charm = 0x5d92,
        Stun = 0x36a4,
        SendFindableNPCs = 0x4613,
        FindPersonRequest = 0x5cea,
        FindPersonReply = 0x7e58,
        Sound = 0x1a30,
        PetBuffWindow = 0x5882,
        LevelAppearance = 0x3bc9,
        Translocate = 0x6580,
        Sacrifice = 0x1821,
        PopupResponse = 0x08a6,
        OnLevelMessage = 0x575b,
        AugmentInfo = 0x0afb,
        Petition = 0x3de3,
        SomeItemPacketMaybe = 0x747c,
        PVPStats = 0x4b15,
        PVPLeaderBoardRequest = 0x04aa,
        PVPLeaderBoardReply = 0x071f,
        PVPLeaderBoardDetailsRequest = 0x3707,
        PVPLeaderBoardDetailsReply = 0x25b7,
        RespawnWindow = 0x0ecb,
        LDoNButton = 0x5327,
        SetStartCity = 0x6326,
        VoiceMacroIn = 0x17fd,
        VoiceMacroOut = 0x409a,
        ItemViewUnknown = 0x465b,
        VetRewardsAvaliable = 0x590e,
        VetClaimRequest = 0x1126,
        VetClaimReply = 0x16d4,
        DisciplineUpdate = 0x759e,
        DisciplineTimer = 0x6989,
        MobUpdate = 0x2c84,
        NPCMoveUpdate = 0x5892,
        CameraEffect = 0x127f,
        SpellEffect = 0x5936,
        RemoveNimbusEffect = 0x7b1e,
        AltCurrency = 0x6b6d,
        AltCurrencyMerchantRequest = 0x5409,
        AltCurrencyMerchantReply = 0x27a2,
        AltCurrencyPurchase = 0x3788,
        AltCurrencySell = 0x40b6,
        AltCurrencySellSelection = 0x532a,
        AltCurrencyReclaim = 0x0339,
        CrystalCountUpdate = 0x467f,
        CrystalCreate = 0x7aee,
        CrystalReclaim = 0x2439,
        Untargetable = 0x053c,
        IncreaseStats = 0x70a3,
        Weblink = 0x6f4b,
        Marquee = 0x502e,
        ItemRecastDelay = 0x15a9,
        DzAddPlayer = 0x4701,
        DzRemovePlayer = 0x1abc,
        DzSwapPlayer = 0x405b,
        DzMakeLeader = 0x543d,
        DzPlayerList = 0x14c6,
        DzJoinExpeditionConfirm = 0x7f4b,
        DzJoinExpeditionReply = 0x1950,
        DzListTimers = 0x7b68,
        DzExpeditionInfo = 0x9119,
        DzExpeditionList = 0x205f,
        DzQuit = 0xb2e3,
        DzMemberStatus = 0x32f0,
        DzLeaderStatus = 0x3de9,
        DzMemberList = 0x5ae4,
        DzExpeditionEndsWarning = 0x383c,
        DzCompass = 0x3e0e,
        DzChooseZone = 0x0b7d,
        ManaUpdate = 0x3791,
        EnduranceUpdate = 0x5f42,
        MobManaUpdate = 0x2404,
        MobEnduranceUpdate = 0x1c81,
        MercenaryDataUpdateRequest = 0x7b89,
        MercenaryDataUpdate = 0x61a4,
        MercenaryDataRequest = 0x11c1,
        MercenaryDataResponse = 0x72ce,
        MercenaryHire = 0x7169,
        MercenaryDismiss = 0x6e83,
        MercenaryTimerRequest = 0x31e4,
        MercenaryTimer = 0x0763,
        MercenaryUnknown1 = 0x5d26,
        MercenaryCommand = 0x27f2,
        MercenarySuspendRequest = 0x4407,
        MercenarySuspendResponse = 0x6f03,
        MercenaryUnsuspendResponse = 0x27a0,
        LootRequest = 0x0adf,
        EndLootRequest = 0x30f7,
        LootItem = 0x4dc9,
        LootComplete = 0x55c4,
        BazaarSearch = 0x39d6,
        TraderDelItem = 0x5829,
        BecomeTrader = 0x61b3,
        TraderShop = 0x31df,
        Trader = 0x4ef5,
        Barter = 0x243a,
        TradeRequest = 0x77b5,
        TradeAcceptClick = 0x69e2,
        TradeRequestAck = 0x14bf,
        TradeCoins = 0x4206,
        FinishTrade = 0x3993,
        CancelTrade = 0x354c,
        TradeMoneyUpdate = 0x68c2,
        MoneyUpdate = 0x640c,
        TradeBusy = 0x5505,
        FinishWindow = 0x7349,
        FinishWindow2 = 0x40ef,
        ItemVerifyRequest = 0x189c,
        ItemVerifyReply = 0x097b,
        ShopPlayerSell = 0x791b,
        ShopRequest = 0x4fed,
        ShopEnd = 0x30a8,
        ShopEndConfirm = 0x3196,
        ShopPlayerBuy = 0x0ddd,
        ShopDelItem = 0x724f,
        ClickObject = 0x4aa1,
        ClickObjectAction = 0x0c1e,
        ClearObject = 0x7a11,
        RecipeDetails = 0x6e02,
        RecipesFavorite = 0x71b1,
        RecipesSearch = 0x6290,
        RecipeReply = 0x1db6,
        RecipeAutoCombine = 0x40d7,
        TradeSkillCombine = 0x579a,
        OpenGuildTributeMaster = 0x378d,
        OpenTributeMaster = 0x7666,
        SelectTribute = 0x79fc,
        TributeItem = 0x4f3e,
        TributeMoney = 0x58fb,
        TributeToggle = 0x241d,
        TributePointUpdate = 0x5300,
        LeaveAdventure = 0x5d18,
        AdventureFinish = 0x400f,
        AdventureInfoRequest = 0x3cb0,
        AdventureInfo = 0x4c54,
        AdventureRequest = 0x2c6c,
        AdventureDetails = 0x5648,
        AdventureData = 0x7171,
        AdventureUpdate = 0x1b01,
        AdventureMerchantRequest = 0x6922,
        AdventureMerchantResponse = 0x3e47,
        AdventureMerchantPurchase = 0x5b72,
        AdventureMerchantSell = 0x2f9b,
        AdventurePointsUpdate = 0x65c3,
        AdventureStatsRequest = 0x5a62,
        AdventureStatsReply = 0x2370,
        AdventureLeaderboardRequest = 0x7093,
        AdventureLeaderboardReply = 0x7f79,
        GroupDisband = 0x4c10,
        GroupInvite = 0x6110,
        GroupFollow = 0x1649,
        GroupUpdate = 0x3abb,
        GroupUpdateB = 0x6194,
        GroupAcknowledge = 0x7323,
        GroupDelete = 0x0f6c,
        CancelInvite = 0x2a50,
        GroupFollow2 = 0x2060,
        GroupInvite2 = 0x32c2,
        GroupDisbandYou = 0x1ae5,
        GroupDisbandOther = 0x74da,
        GroupLeaderChange = 0x21b4,
        GroupRoles = 0x70e2,
        GroupMakeLeader = 0x4229,
        DoGroupLeadershipAbility = 0x6eae,
        GroupLeadershipAAUpdate = 0x02cf,
        GroupMentor = 0x3342,
        InspectBuffs = 0x486c,
        LFGCommand = 0x6060,
        LFGGetMatchesRequest = 0x0340,
        LFGGetMatchesResponse = 0x5048,
        LFPGetMatchesRequest = 0x4d7d,
        LFPGetMatchesResponse = 0x22c6,
        LFPCommand = 0x49a9,
        RaidInvite = 0x55ac,
        RaidUpdate = 0x3973,
        Taunt = 0x2703,
        CombatAbility = 0x3eba,
        SenseTraps = 0x02af,
        PickPocket = 0x39e8,
        DisarmTraps = 0x78bf,
        Disarm = 0x5ec8,
        Sneak = 0x5d55,
        Fishing = 0x1e2a,
        InstillDoubt = 0x640e,
        FeignDeath = 0x52fa,
        Mend = 0x0ecf,
        LDoNOpen = 0x3d5c,
        TaskDescription = 0x3714,
        TaskActivity = 0x08d3,
        CompletedTasks = 0x4eba,
        TaskActivityComplete = 0x5e19,
        AcceptNewTask = 0x0a23,
        CancelTask = 0x39f0,
        TaskMemberList = 0x5727,
        OpenNewTasksWindow = 0x48a2,
        AvaliableTask = 0x36e8,
        TaskHistoryRequest = 0x5f1c,
        TaskHistoryReply = 0x3d05,
        NewTitlesAvailable = 0x0d32,
        RequestTitles = 0x6344,
        SendTitleList = 0x2d08,
        SetTitle = 0x6527,
        SetTitleReply = 0x4c21,
        PlayMP3 = 0x5770,
        COUNT
    };

    static const OpCodeTranslation toCanonical[] = {
        { 0x7a09, CanonicalOp::SendLoginInfo },
        { 0x7499, CanonicalOp::ApproveWorld },
        { 0x7ceb, CanonicalOp::LogServer },
        { 0x00d2, CanonicalOp::SendCharInfo },
        { 0x590d, CanonicalOp::ExpansionInfo },
        { 0x507a, CanonicalOp::GuildsList },
        { 0x578f, CanonicalOp::EnterWorld },
        { 0x6259, CanonicalOp::PostEnterWorld },
        { 0x5475, CanonicalOp::SendMaxCharacters },
        { 0x7acc, CanonicalOp::SendMembership },
        { 0x057b, CanonicalOp::SendMembershipDetails },
        { 0x6773, CanonicalOp::CharacterCreateRequest },
        { 0x6bbf, CanonicalOp::CharacterCreate },
        { 0x1808, CanonicalOp::DeleteCharacter },
        { 0x5954, CanonicalOp::RandomNameGenerator },
        { 0x56a2, CanonicalOp::ApproveName },
        { 0x0c22, CanonicalOp::MOTD },
        { 0x1bc5, CanonicalOp::SetChatServer },
        { 0x7eec, CanonicalOp::SetChatServer2 },
        { 0x4c44, CanonicalOp::ZoneServerInfo },
        { 0x4493, CanonicalOp::WorldComplete },
        { 0x2301, CanonicalOp::WorldUnknown001 },
        { 0x46c6, CanonicalOp::FloatListThing },
        { 0x4cb4, CanonicalOp::ZoneUnavail },
        { 0x23c1, CanonicalOp::WorldClientReady },
        { 0x471d, CanonicalOp::AckPacket },
        { 0x5089, CanonicalOp::ZoneEntry },
        { 0x7887, CanonicalOp::ReqNewZone },
        { 0x1795, CanonicalOp::NewZone },
        { 0x5237, CanonicalOp::ZoneSpawns },
        { 0x6506, CanonicalOp::PlayerProfile },
        { 0x5070, CanonicalOp::TimeOfDay },
        { 0x1eec, CanonicalOp::LevelUpdate },
        { 0x2a79, CanonicalOp::Stamina },
        { 0x3fcf, CanonicalOp::RequestClientZoneChange },
        { 0x2d18, CanonicalOp::ZoneChange },
        { 0x0971, CanonicalOp::SpawnAppearance },
        { 0x4707, CanonicalOp::ChangeSize },
        { 0x5961, CanonicalOp::TributeUpdate },
        { 0x073d, CanonicalOp::TributeTimer },
        { 0x729b, CanonicalOp::SendTributes },
        { 0x1877, CanonicalOp::SendGuildTributes },
        { 0x4254, CanonicalOp::TributeInfo },
        { 0x661e, CanonicalOp::Weather },
        { 0x35fa, CanonicalOp::ReqClientSpawn },
        { 0x7291, CanonicalOp::SpawnDoor },
        { 0x6fca, CanonicalOp::GroundSpawn },
        { 0x69a4, CanonicalOp::SendZonepoints },
        { 0x3033, CanonicalOp::BlockedBuffs },
        { 0x0de7, CanonicalOp::RemoveBlockedBuffs },
        { 0x34cb, CanonicalOp::ClearBlockedBuffs },
        { 0x5ae2, CanonicalOp::WorldObjectsSent },
        { 0x5f8e, CanonicalOp::SendExpZonein },
        { 0x66b5, CanonicalOp::SendAATable },
        { 0x0f50, CanonicalOp::ClearAA },
        { 0x6da5, CanonicalOp::ClearLeadershipAbilities },
        { 0x7a27, CanonicalOp::RespondAA },
        { 0x66f0, CanonicalOp::UpdateAA },
        { 0x43c8, CanonicalOp::SendAAStats },
        { 0x7d14, CanonicalOp::AAExpUpdate },
        { 0x20ed, CanonicalOp::ExpUpdate },
        { 0x2828, CanonicalOp::HPUpdate },
        { 0x5467, CanonicalOp::ManaChange },
        { 0x0876, CanonicalOp::TGB },
        { 0x0083, CanonicalOp::SpecialMesg },
        { 0x12a6, CanonicalOp::GuildMemberList },
        { 0x3e13, CanonicalOp::GuildMOTD },
        { 0x5ca6, CanonicalOp::CharInventory },
        { 0x7994, CanonicalOp::WearChange },
        { 0x7dfc, CanonicalOp::ClientUpdate },
        { 0x345d, CanonicalOp::ClientReady },
        { 0x444d, CanonicalOp::SetServerFilter },
        { 0x36e0, CanonicalOp::GetGuildMOTD },
        { 0x4f1f, CanonicalOp::GetGuildMOTDReply },
        { 0x69b9, CanonicalOp::GuildMemberUpdate },
        { 0x7099, CanonicalOp::GuildInvite },
        { 0x1444, CanonicalOp::GuildRemove },
        { 0x67e3, CanonicalOp::GuildPeace },
        { 0x0b0b, CanonicalOp::SetGuildMOTD },
        { 0x1ffb, CanonicalOp::GuildWar },
        { 0x7e09, CanonicalOp::GuildLeader },
        { 0x3708, CanonicalOp::GuildDelete },
        { 0x7053, CanonicalOp::GuildInviteAccept },
        { 0x2d4e, CanonicalOp::GuildDemote },
        { 0x6a98, CanonicalOp::GuildPromote },
        { 0x5053, CanonicalOp::GuildPublicNote },
        { 0x3f35, CanonicalOp::GuildManageBanker },
        { 0x5134, CanonicalOp::GuildBank },
        { 0x0b9c, CanonicalOp::SetGuildRank },
        { 0x2958, CanonicalOp::GuildUpdateURLAndChannel },
        { 0x7326, CanonicalOp::GuildStatus },
        { 0x76d9, CanonicalOp::GuildCreate },
        { 0x08c1, CanonicalOp::GMServers },
        { 0x3ae1, CanonicalOp::GMBecomeNPC },
        { 0x62ac, CanonicalOp::GMZoneRequest },
        { 0x7e1a, CanonicalOp::GMZoneRequest2 },
        { 0x7d8e, CanonicalOp::GMGoto },
        { 0x357c, CanonicalOp::GMSearchCorpse },
        { 0x79c5, CanonicalOp::GMHideMe },
        { 0x607e, CanonicalOp::GMDelCorpse },
        { 0x6db5, CanonicalOp::GMApproval },
        { 0x2097, CanonicalOp::GMToggle },
        { 0x486f, CanonicalOp::GMSummon },
        { 0x1cfd, CanonicalOp::GMEmoteZone },
        { 0x458e, CanonicalOp::GMEmoteWorld },
        { 0x4a8f, CanonicalOp::GMFind },
        { 0x26a7, CanonicalOp::GMKick },
        { 0x51d3, CanonicalOp::GMKill },
        { 0x035f, CanonicalOp::GMNameChange },
        { 0x46ce, CanonicalOp::GMLastName },
        { 0x57bc, CanonicalOp::InspectRequest },
        { 0x71ac, CanonicalOp::InspectAnswer },
        { 0x4d25, CanonicalOp::InspectMessageUpdate },
        { 0x318f, CanonicalOp::BeginCast },
        { 0x43af, CanonicalOp::ColoredText },
        { 0x384a, CanonicalOp::ConsentResponse },
        { 0x217c, CanonicalOp::MemorizeSpell },
        { 0x0efa, CanonicalOp::SwapSpell },
        { 0x1287, CanonicalOp::CastSpell },
        { 0x742b, CanonicalOp::Consider },
        { 0x1024, CanonicalOp::FormattedMessage },
        { 0x213f, CanonicalOp::SimpleMessage },
        { 0x659c, CanonicalOp::Buff },
        { 0x312a, CanonicalOp::Illusion },
        { 0x5f44, CanonicalOp::MoneyOnCorpse },
        { 0x106b, CanonicalOp::RandomReply },
        { 0x2382, CanonicalOp::DenyResponse },
        { 0x004c, CanonicalOp::SkillUpdate },
        { 0x4b64, CanonicalOp::GMTrainSkillConfirm },
        { 0x7b10, CanonicalOp::RandomReq },
        { 0x6517, CanonicalOp::Death },
        { 0x1966, CanonicalOp::GMTraining },
        { 0x4d6b, CanonicalOp::GMEndTraining },
        { 0x2a85, CanonicalOp::GMTrainSkill },
        { 0x7177, CanonicalOp::Animation },
        { 0x6703, CanonicalOp::Begging },
        { 0x1fd1, CanonicalOp::Consent },
        { 0x7a45, CanonicalOp::ConsentDeny },
        { 0x241e, CanonicalOp::AutoFire },
        { 0x0159, CanonicalOp::PetCommands },
        { 0x794a, CanonicalOp::PetHoTT },
        { 0x3358, CanonicalOp::DeleteSpell },
        { 0x0423, CanonicalOp::Surname },
        { 0x3fb0, CanonicalOp::ClearSurname },
        { 0x5578, CanonicalOp::FaceChange },
        { 0x260a, CanonicalOp::SenseHeading },
        { 0x744c, CanonicalOp::Action },
        { 0x5204, CanonicalOp::ConsiderCorpse },
        { 0x49e1, CanonicalOp::HideCorpse },
        { 0x0904, CanonicalOp::CorpseDrag },
        { 0x7037, CanonicalOp::CorpseDrop },
        { 0x73f4, CanonicalOp::Bug },
        { 0x5602, CanonicalOp::Feedback },
        { 0x6f14, CanonicalOp::Report },
        { 0x6f15, CanonicalOp::Damage },
        { 0x2b2d, CanonicalOp::ChannelMessage },
        { 0x4478, CanonicalOp::Assist },
        { 0x27f8, CanonicalOp::AssistGroup },
        { 0x0bcf, CanonicalOp::MoveCoin },
        { 0x08d8, CanonicalOp::ZonePlayerToBind },
        { 0x1219, CanonicalOp::KeyRing },
        { 0x674b, CanonicalOp::WhoAllRequest },
        { 0x578c, CanonicalOp::WhoAllResponse },
        { 0x3956, CanonicalOp::FriendsWho },
        { 0x43a3, CanonicalOp::ConfirmDelete },
        { 0x4ac6, CanonicalOp::Logout },
        { 0x1745, CanonicalOp::Rewind },
        { 0x58e2, CanonicalOp::TargetCommand },
        { 0x67fe, CanonicalOp::Hide },
        { 0x31f4, CanonicalOp::Jump },
        { 0x28ec, CanonicalOp::Camp },
        { 0x373b, CanonicalOp::Emote },
        { 0x009f, CanonicalOp::SetRunMode },
        { 0x791e, CanonicalOp::BankerChange },
        { 0x075d, CanonicalOp::TargetMouse },
        { 0x37b1, CanonicalOp::MobHealth },
        { 0x0272, CanonicalOp::TargetHoTT },
        { 0x4f4b, CanonicalOp::TargetBuffs },
        { 0x4d59, CanonicalOp::XTargetResponse },
        { 0x3763, CanonicalOp::XTargetRequest },
        { 0x672f, CanonicalOp::XTargetAutoAddHaters },
        { 0x3377, CanonicalOp::BuffCreate },
        { 0x64f2, CanonicalOp::BuffRemoveRequest },
        { 0x7280, CanonicalOp::DeleteSpawn },
        { 0x109d, CanonicalOp::AutoAttack },
        { 0x3526, CanonicalOp::AutoAttack2 },
        { 0x4b70, CanonicalOp::Consume },
        { 0x32ee, CanonicalOp::MoveItem },
        { 0x18ad, CanonicalOp::DeleteItem },
        { 0x01b8, CanonicalOp::DeleteCharge },
        { 0x368e, CanonicalOp::ItemPacket },
        { 0x70c0, CanonicalOp::ItemLinkResponse },
        { 0x4cef, CanonicalOp::ItemLinkClick },
        { 0x6b5c, CanonicalOp::ItemPreview },
        { 0x6097, CanonicalOp::NewSpawn },
        { 0x17e5, CanonicalOp::Track },
        { 0x695e, CanonicalOp::TrackTarget },
        { 0x4577, CanonicalOp::TrackUnknown },
        { 0x3a8f, CanonicalOp::ClickDoor },
        { 0x08e8, CanonicalOp::MoveDoor },
        { 0x700c, CanonicalOp::RemoveAllDoors },
        { 0x51fd, CanonicalOp::EnvDamage },
        { 0x4211, CanonicalOp::BoardBoat },
        { 0x7617, CanonicalOp::LeaveBoat },
        { 0x0ae7, CanonicalOp::ControlBoat },
        { 0x5306, CanonicalOp::Forage },
        { 0x2219, CanonicalOp::SafeFallSuccess },
        { 0x760d, CanonicalOp::RezzComplete },
        { 0x3c21, CanonicalOp::RezzRequest },
        { 0x701c, CanonicalOp::RezzAnswer },
        { 0x52e5, CanonicalOp::Shielding },
        { 0x3af1, CanonicalOp::RequestDuel },
        { 0x2c57, CanonicalOp::MobRename },
        { 0x661b, CanonicalOp::AugmentItem },
        { 0x34a7, CanonicalOp::WeaponEquip1 },
        { 0x559a, CanonicalOp::PlayerStateAdd },
        { 0x2d25, CanonicalOp::PlayerStateRemove },
        { 0x31e6, CanonicalOp::ApplyPoison },
        { 0x4a39, CanonicalOp::Save },
        { 0x7cb8, CanonicalOp::TestBuff },
        { 0x100e, CanonicalOp::CustomTitles },
        { 0x3a54, CanonicalOp::Split },
        { 0x4e56, CanonicalOp::YellForHelp },
        { 0x261d, CanonicalOp::LoadSpellSet },
        { 0x7677, CanonicalOp::Bandolier },
        { 0x1a3e, CanonicalOp::PotionBelt },
        { 0x6a46, CanonicalOp::DuelResponse },
        { 0x68d3, CanonicalOp::DuelResponse2 },
        { 0x600d, CanonicalOp::SaveOnZoneReq },
        { 0x72df, CanonicalOp::ReadBook },
        { 0x23b9, CanonicalOp::Dye },
        { 0x048c, CanonicalOp::InterruptCast },
        { 0x424e, CanonicalOp::AAAction },
        { 0x74bd, CanonicalOp::LeadershipExpToggle },
        { 0x2797, CanonicalOp::LeadershipExpUpdate },
        { 0x6c55, CanonicalOp::PurchaseLeadershipAA },
        { 0x1fb5, CanonicalOp::MarkNPC },
        { 0x5a58, CanonicalOp::MarkRaidNPC },
        { 0x2003, CanonicalOp::ClearNPCMarks },
        { 0x20d3, CanonicalOp::ClearRaidNPCMarks },
        { 0x4c9d, CanonicalOp::DelegateAbility },
        { 0x5d92, CanonicalOp::Charm },
        { 0x36a4, CanonicalOp::Stun },
        { 0x4613, CanonicalOp::SendFindableNPCs },
        { 0x5cea, CanonicalOp::FindPersonRequest },
        { 0x7e58, CanonicalOp::FindPersonReply },
        { 0x1a30, CanonicalOp::Sound },
        { 0x5882, CanonicalOp::PetBuffWindow },
        { 0x3bc9, CanonicalOp::LevelAppearance },
        { 0x6580, CanonicalOp::Translocate },
        { 0x1821, CanonicalOp::Sacrifice },
        { 0x08a6, CanonicalOp::PopupResponse },
        { 0x575b, CanonicalOp::OnLevelMessage },
        { 0x0afb, CanonicalOp::AugmentInfo },
        { 0x3de3, CanonicalOp::Petition },
        { 0x747c, CanonicalOp::SomeItemPacketMaybe },
        { 0x4b15, CanonicalOp::PVPStats },
        { 0x04aa, CanonicalOp::PVPLeaderBoardRequest },
        { 0x071f, CanonicalOp::PVPLeaderBoardReply },
        { 0x3707, CanonicalOp::PVPLeaderBoardDetailsRequest },
        { 0x25b7, CanonicalOp::PVPLeaderBoardDetailsReply },
        { 0x0ecb, CanonicalOp::RespawnWindow },
        { 0x5327, CanonicalOp::LDoNButton },
        { 0x6326, CanonicalOp::SetStartCity },
        { 0x17fd, CanonicalOp::VoiceMacroIn },
        { 0x409a, CanonicalOp::VoiceMacroOut },
        { 0x465b, CanonicalOp::ItemViewUnknown },
        { 0x590e, CanonicalOp::VetRewardsAvaliable },
        { 0x1126, CanonicalOp::VetClaimRequest },
        { 0x16d4, CanonicalOp::VetClaimReply },
        { 0x759e, CanonicalOp::DisciplineUpdate },
        { 0x6989, CanonicalOp::DisciplineTimer },
        { 0x2c84, CanonicalOp::MobUpdate },
        { 0x5892, CanonicalOp::NPCMoveUpdate },
        { 0x127f, CanonicalOp::CameraEffect },
        { 0x5936, CanonicalOp::SpellEffect },
        { 0x7b1e, CanonicalOp::RemoveNimbusEffect },
        { 0x6b6d, CanonicalOp::AltCurrency },
        { 0x5409, CanonicalOp::AltCurrencyMerchantRequest },
        { 0x27a2, CanonicalOp::AltCurrencyMerchantReply },
        { 0x3788, CanonicalOp::AltCurrencyPurchase },
        { 0x40b6, CanonicalOp::AltCurrencySell },
        { 0x532a, CanonicalOp::AltCurrencySellSelection },
        { 0x0339, CanonicalOp::AltCurrencyReclaim },
        { 0x467f, CanonicalOp::CrystalCountUpdate },
        { 0x7aee, CanonicalOp::CrystalCreate },
        { 0x2439, CanonicalOp::CrystalReclaim },
        { 0x053c, CanonicalOp::Untargetable },
        { 0x70a3, CanonicalOp::IncreaseStats },
        { 0x6f4b, CanonicalOp::Weblink },
        { 0x502e, CanonicalOp::Marquee },
        { 0x15a9, CanonicalOp::ItemRecastDelay },
        { 0x4701, CanonicalOp::DzAddPlayer },
        { 0x1abc, CanonicalOp::DzRemovePlayer },
        { 0x405b, CanonicalOp::DzSwapPlayer },
        { 0x543d, CanonicalOp::DzMakeLeader },
        { 0x14c6, CanonicalOp::DzPlayerList },
        { 0x7f4b, CanonicalOp::DzJoinExpeditionConfirm },
        { 0x1950, CanonicalOp::DzJoinExpeditionReply },
        { 0x7b68, CanonicalOp::DzListTimers },
        { 0x9119, CanonicalOp::DzExpeditionInfo },
        { 0x205f, CanonicalOp::DzExpeditionList },
        { 0xb2e3, CanonicalOp::DzQuit },
        { 0x32f0, CanonicalOp::DzMemberStatus },
        { 0x3de9, CanonicalOp::DzLeaderStatus },
        { 0x5ae4, CanonicalOp::DzMemberList },
        { 0x383c, CanonicalOp::DzExpeditionEndsWarning },
        { 0x3e0e, CanonicalOp::DzCompass },
        { 0x0b7d, CanonicalOp::DzChooseZone },
        { 0x3791, CanonicalOp::ManaUpdate },
        { 0x5f42, CanonicalOp::EnduranceUpdate },
        { 0x2404, CanonicalOp::MobManaUpdate },
        { 0x1c81, CanonicalOp::MobEnduranceUpdate },
        { 0x7b89, CanonicalOp::MercenaryDataUpdateRequest },
        { 0x61a4, CanonicalOp::MercenaryDataUpdate },
        { 0x11c1, CanonicalOp::MercenaryDataRequest },
        { 0x72ce, CanonicalOp::MercenaryDataResponse },
        { 0x7169, CanonicalOp::MercenaryHire },
        { 0x6e83, CanonicalOp::MercenaryDismiss },
        { 0x31e4, CanonicalOp::MercenaryTimerRequest },
        { 0x0763, CanonicalOp::MercenaryTimer },
        { 0x5d26, CanonicalOp::MercenaryUnknown1 },
        { 0x27f2, CanonicalOp::MercenaryCommand },
        { 0x4407, CanonicalOp::MercenarySuspendRequest },
        { 0x6f03, CanonicalOp::MercenarySuspendResponse },
        { 0x27a0, CanonicalOp::MercenaryUnsuspendResponse },
        { 0x0adf, CanonicalOp::LootRequest },
        { 0x30f7, CanonicalOp::EndLootRequest },
        { 0x4dc9, CanonicalOp::LootItem },
        { 0x55c4, CanonicalOp::LootComplete },
        { 0x39d6, CanonicalOp::BazaarSearch },
        { 0x5829, CanonicalOp::TraderDelItem },
        { 0x61b3, CanonicalOp::BecomeTrader },
        { 0x31df, CanonicalOp::TraderShop },
        { 0x4ef5, CanonicalOp::Trader },
        { 0x243a, CanonicalOp::Barter },
        { 0x77b5, CanonicalOp::TradeRequest },
        { 0x69e2, CanonicalOp::TradeAcceptClick },
        { 0x14bf, CanonicalOp::TradeRequestAck },
        { 0x4206, CanonicalOp::TradeCoins },
        { 0x3993, CanonicalOp::FinishTrade },
        { 0x354c, CanonicalOp::CancelTrade },
        { 0x68c2, CanonicalOp::TradeMoneyUpdate },
        { 0x640c, CanonicalOp::MoneyUpdate },
        { 0x5505, CanonicalOp::TradeBusy },
        { 0x7349, CanonicalOp::FinishWindow },
        { 0x40ef, CanonicalOp::FinishWindow2 },
        { 0x189c, CanonicalOp::ItemVerifyRequest },
        { 0x097b, CanonicalOp::ItemVerifyReply },
        { 0x791b, CanonicalOp::ShopPlayerSell },
        { 0x4fed, CanonicalOp::ShopRequest },
        { 0x30a8, CanonicalOp::ShopEnd },
        { 0x3196, CanonicalOp::ShopEndConfirm },
        { 0x0ddd, CanonicalOp::ShopPlayerBuy },
        { 0x724f, CanonicalOp::ShopDelItem },
        { 0x4aa1, CanonicalOp::ClickObject },
        { 0x0c1e, CanonicalOp::ClickObjectAction },
        { 0x7a11, CanonicalOp::ClearObject },
        { 0x6e02, CanonicalOp::RecipeDetails },
        { 0x71b1, CanonicalOp::RecipesFavorite },
        { 0x6290, CanonicalOp::RecipesSearch },
        { 0x1db6, CanonicalOp::RecipeReply },
        { 0x40d7, CanonicalOp::RecipeAutoCombine },
        { 0x579a, CanonicalOp::TradeSkillCombine },
        { 0x378d, CanonicalOp::OpenGuildTributeMaster },
        { 0x7666, CanonicalOp::OpenTributeMaster },
        { 0x79fc, CanonicalOp::SelectTribute },
        { 0x4f3e, CanonicalOp::TributeItem },
        { 0x58fb, CanonicalOp::TributeMoney },
        { 0x241d, CanonicalOp::TributeToggle },
        { 0x5300, CanonicalOp::TributePointUpdate },
        { 0x5d18, CanonicalOp::LeaveAdventure },
        { 0x400f, CanonicalOp::AdventureFinish },
        { 0x3cb0, CanonicalOp::AdventureInfoRequest },
        { 0x4c54, CanonicalOp::AdventureInfo },
        { 0x2c6c, CanonicalOp::AdventureRequest },
        { 0x5648, CanonicalOp::AdventureDetails },
        { 0x7171, CanonicalOp::AdventureData },
        { 0x1b01, CanonicalOp::AdventureUpdate },
        { 0x6922, CanonicalOp::AdventureMerchantRequest },
        { 0x3e47, CanonicalOp::AdventureMerchantResponse },
        { 0x5b72, CanonicalOp::AdventureMerchantPurchase },
        { 0x2f9b, CanonicalOp::AdventureMerchantSell },
        { 0x65c3, CanonicalOp::AdventurePointsUpdate },
        { 0x5a62, CanonicalOp::AdventureStatsRequest },
        { 0x2370, CanonicalOp::AdventureStatsReply },
        { 0x7093, CanonicalOp::AdventureLeaderboardRequest },
        { 0x7f79, CanonicalOp::AdventureLeaderboardReply },
        { 0x4c10, CanonicalOp::GroupDisband },
        { 0x6110, CanonicalOp::GroupInvite },
        { 0x1649, CanonicalOp::GroupFollow },
        { 0x3abb, CanonicalOp::GroupUpdate },
        { 0x6194, CanonicalOp::GroupUpdateB },
        { 0x7323, CanonicalOp::GroupAcknowledge },
        { 0x0f6c, CanonicalOp::GroupDelete },
        { 0x2a50, CanonicalOp::CancelInvite },
        { 0x2060, CanonicalOp::GroupFollow2 },
        { 0x32c2, CanonicalOp::GroupInvite2 },
        { 0x1ae5, CanonicalOp::GroupDisbandYou },
        { 0x74da, CanonicalOp::GroupDisbandOther },
        { 0x21b4, CanonicalOp::GroupLeaderChange },
        { 0x70e2, CanonicalOp::GroupRoles },
        { 0x4229, CanonicalOp::GroupMakeLeader },
        { 0x6eae, CanonicalOp::DoGroupLeadershipAbility },
        { 0x02cf, CanonicalOp::GroupLeadershipAAUpdate },
        { 0x3342, CanonicalOp::GroupMentor },
        { 0x486c, CanonicalOp::InspectBuffs },
        { 0x6060, CanonicalOp::LFGCommand },
        { 0x0340, CanonicalOp::LFGGetMatchesRequest },
        { 0x5048, CanonicalOp::LFGGetMatchesResponse },
        { 0x4d7d, CanonicalOp::LFPGetMatchesRequest },
        { 0x22c6, CanonicalOp::LFPGetMatchesResponse },
        { 0x49a9, CanonicalOp::LFPCommand },
        { 0x55ac, CanonicalOp::RaidInvite },
        { 0x3973, CanonicalOp::RaidUpdate },
        { 0x2703, CanonicalOp::Taunt },
        { 0x3eba, CanonicalOp::CombatAbility },
        { 0x02af, CanonicalOp::SenseTraps },
        { 0x39e8, CanonicalOp::PickPocket },
        { 0x78bf, CanonicalOp::DisarmTraps },
        { 0x5ec8, CanonicalOp::Disarm },
        { 0x5d55, CanonicalOp::Sneak },
        { 0x1e2a, CanonicalOp::Fishing },
        { 0x640e, CanonicalOp::InstillDoubt },
        { 0x52fa, CanonicalOp::FeignDeath },
        { 0x0ecf, CanonicalOp::Mend },
        { 0x3d5c, CanonicalOp::LDoNOpen },
        { 0x3714, CanonicalOp::TaskDescription },
        { 0x08d3, CanonicalOp::TaskActivity },
        { 0x4eba, CanonicalOp::CompletedTasks },
        { 0x5e19, CanonicalOp::TaskActivityComplete },
        { 0x0a23, CanonicalOp::AcceptNewTask },
        { 0x39f0, CanonicalOp::CancelTask },
        { 0x5727, CanonicalOp::TaskMemberList },
        { 0x48a2, CanonicalOp::OpenNewTasksWindow },
        { 0x36e8, CanonicalOp::AvaliableTask },
        { 0x5f1c, CanonicalOp::TaskHistoryRequest },
        { 0x3d05, CanonicalOp::TaskHistoryReply },
        { 0x0d32, CanonicalOp::NewTitlesAvailable },
        { 0x6344, CanonicalOp::RequestTitles },
        { 0x2d08, CanonicalOp::SendTitleList },
        { 0x6527, CanonicalOp::SetTitle },
        { 0x4c21, CanonicalOp::SetTitleReply },
        { 0x5770, CanonicalOp::PlayMP3 }
    };
}

#endif//_EQP_OPCODES_ROF2_HPP_
