
#ifndef _EQP_OPCODES_SOD_HPP_
#define _EQP_OPCODES_SOD_HPP_

#include "define.hpp"
#include "opcodes_canonical.hpp"
#include "opcode_translate.hpp"

namespace SeedsOfDestruction
{
    enum Op : uint16_t
    {
        SendLoginInfo = 0x0ff4,
        ApproveWorld = 0x701f,
        LogServer = 0x4762,
        SendCharInfo = 0x0f14,
        ExpansionInfo = 0x7519,
        GuildsList = 0x5b0b,
        EnterWorld = 0x1c20,
        PostEnterWorld = 0x7c94,
        SendSpellChecksum = 0x5bad,
        SendSkillCapsChecksum = 0x5d24,
        DeleteCharacter = 0x0254,
        CharacterCreateRequest = 0x4463,
        CharacterCreate = 0x1513,
        RandomNameGenerator = 0x3604,
        ApproveName = 0x413f,
        MOTD = 0x192e,
        SetChatServer = 0x7f2b,
        SetChatServer2 = 0x11f3,
        ZoneServerInfo = 0x5da4,
        WorldComplete = 0x37db,
        WorldUnknown001 = 0x2c4c,
        FloatListThing = 0x10b5,
        ZoneUnavail = 0x7930,
        WorldClientReady = 0x1a84,
        AckPacket = 0x3594,
        ZoneEntry = 0x5a6b,
        ReqNewZone = 0x43ac,
        NewZone = 0x5ca5,
        ZoneSpawns = 0x72f8,
        PlayerProfile = 0x6022,
        TimeOfDay = 0x6015,
        LevelUpdate = 0x6a99,
        Stamina = 0x3e50,
        RequestClientZoneChange = 0x4885,
        ZoneChange = 0x051b,
        SpawnAppearance = 0x10b7,
        TributeUpdate = 0x399b,
        TributeTimer = 0x4423,
        TaskDescription = 0x7b77,
        TaskActivity = 0x0525,
        CompletedTasks = 0x5412,
        Weather = 0x2641,
        SendAATable = 0x322f,
        UpdateAA = 0x466c,
        RespondAA = 0x0142,
        ReqClientSpawn = 0x1436,
        SpawnDoor = 0x102f,
        GroundSpawn = 0x33e5,
        SendZonepoints = 0x5821,
        SendAAStats = 0x57a3,
        WorldObjectsSent = 0x7b73,
        BlockedBuffs = 0x0baa,
        RemoveBlockedBuffs = 0x064d,
        ClearBlockedBuffs = 0x4027,
        SendExpZonein = 0x69cd,
        SendTributes = 0x4786,
        TributeInfo = 0x4cc6,
        SendGuildTributes = 0x26c4,
        AAExpUpdate = 0x3088,
        ExpUpdate = 0x0e98,
        HPUpdate = 0x538f,
        ManaChange = 0x50c2,
        TGB = 0x2d74,
        SpecialMesg = 0x074f,
        GuildMemberList = 0x51bc,
        GuildMOTD = 0xd677,
        CharInventory = 0x709d,
        WearChange = 0x231f,
        ClientUpdate = 0x7062,
        ClientReady = 0x6759,
        SetServerFilter = 0x7312,
        GetGuildMOTD = 0x189e,
        GetGuildMOTDReply = 0x7a16,
        GuildMemberUpdate = 0x41c0,
        GuildInvite = 0x4843,
        GuildRemove = 0x2b9d,
        GuildPeace = 0x3f21,
        SetGuildMOTD = 0x481f,
        GuildList = 0x5b0b,
        GuildWar = 0x7bfb,
        GuildLeader = 0x1055,
        GuildDelete = 0x75d0,
        GuildInviteAccept = 0x5f25,
        GuildDemote = 0x15b2,
        GuildPublicNote = 0x2dbd,
        GuildManageBanker = 0x11bc,
        GuildBank = 0x0fce,
        SetGuildRank = 0x4ffe,
        GuildUpdateURLAndChannel = 0x5422,
        GuildStatus = 0x5479,
        LFGuild = 0x40e8,
        GMServers = 0x6989,
        GMBecomeNPC = 0x56e7,
        GMZoneRequest = 0x4578,
        GMZoneRequest2 = 0x1912,
        GMGoto = 0x0402,
        GMSearchCorpse = 0x7872,
        GMHideMe = 0x34a1,
        GMDelCorpse = 0x0dda,
        GMApproval = 0x72fa,
        GMToggle = 0x7566,
        GMSummon = 0x596d,
        GMEmoteZone = 0x3e7c,
        GMEmoteWorld = 0x5298,
        GMFind = 0x6e27,
        GMKick = 0x799c,
        GMKill = 0x6685,
        GMNameChange = 0x565d,
        GMLastName = 0x3563,
        InspectAnswer = 0x4938,
        Action2 = 0x7e4d,
        BeginCast = 0x0d5a,
        ColoredText = 0x569a,
        ConsentResponse = 0x6e47,
        MemorizeSpell = 0x8543,
        SwapSpell = 0x3fd2,
        CastSpell = 0x3582,
        Consider = 0x6024,
        FormattedMessage = 0x1318,
        SimpleMessage = 0x5448,
        Buff = 0x7ea8,
        Illusion = 0x48f9,
        MoneyOnCorpse = 0x6546,
        RandomReply = 0x6cdc,
        DenyResponse = 0x7ce7,
        SkillUpdate = 0x7f01,
        GMTrainSkillConfirm = 0x7ae1,
        RandomReq = 0x777c,
        Death = 0x1b85,
        GMTraining = 0x7b64,
        GMEndTraining = 0x3c02,
        GMTrainSkill = 0x7686,
        Animation = 0x47d3,
        Begging = 0x6d37,
        Consent = 0x6bb9,
        ConsentDeny = 0x01e3,
        AutoFire = 0x1bd4,
        PetCommands = 0x3ad6,
        DeleteSpell = 0x0736,
        Surname = 0x7547,
        ClearSurname = 0x2edd,
        FaceChange = 0x5658,
        SenseHeading = 0x3887,
        Action = 0x2c27,
        ConsiderCorpse = 0x37a7,
        HideCorpse = 0x1842,
        CorpseDrag = 0x5a6f,
        CorpseDrop = 0x5a01,
        Bug = 0x002b,
        Feedback = 0x0d1d,
        Report = 0x6884,
        Damage = 0x7e4d,
        ChannelMessage = 0x2e79,
        Assist = 0x2b59,
        AssistGroup = 0x5af6,
        MoveCoin = 0x1fcd,
        ZonePlayerToBind = 0x1d3f,
        KeyRing = 0x0a18,
        WhoAllRequest = 0x177a,
        WhoAllResponse = 0x31f3,
        FriendsWho = 0x6a90,
        ConfirmDelete = 0x3d00,
        Logout = 0x66e0,
        Rewind = 0x4b7b,
        TargetCommand = 0x17f7,
        InspectRequest = 0x4892,
        Hide = 0x1d22,
        Jump = 0x6c16,
        Camp = 0x3eec,
        Emote = 0x7434,
        SetRunMode = 0x07fb,
        BankerChange = 0x21e9,
        TargetMouse = 0x7bbb,
        MobHealth = 0x47ea,
        InitialMobHealth = 0x2d25,
        TargetHoTT = 0x3ec7,
        TargetBuffs = 0x3df8,
        BuffRemoveRequest = 0x6f9d,
        DeleteSpawn = 0x3164,
        AutoAttack = 0x3d86,
        AutoAttack2 = 0x4ca1,
        Consume = 0x7ce4,
        MoveItem = 0x7f56,
        DeleteItem = 0x36f8,
        DeleteCharge = 0x1df9,
        ItemPacket = 0x34f8,
        ItemLinkResponse = 0x2bad,
        ItemLinkClick = 0x3c66,
        NewSpawn = 0x5c29,
        Track = 0x4817,
        TrackTarget = 0x7337,
        TrackUnknown = 0x7b56,
        ClickDoor = 0x1516,
        MoveDoor = 0x6e97,
        RemoveAllDoors = 0x1a58,
        EnvDamage = 0x5ac4,
        BoardBoat = 0x5cd3,
        Forage = 0x7b05,
        LeaveBoat = 0x7554,
        ControlBoat = 0x5bd9,
        SafeFallSuccess = 0x6ad2,
        RezzComplete = 0x42d0,
        RezzRequest = 0x0976,
        RezzAnswer = 0x6e1c,
        Shielding = 0x2f6a,
        RequestDuel = 0x79e0,
        MobRename = 0x0a1d,
        AugmentItem = 0x0370,
        WeaponEquip1 = 0x719e,
        PlayerStateAdd = 0x7b6e,
        PlayerStateRemove = 0x19a8,
        ApplyPoison = 0x405b,
        Save = 0x5c85,
        TestBuff = 0x5fc7,
        DestructableRelated = 0x5ea1,
        CustomTitles = 0x1b26,
        Split = 0x53f9,
        YellForHelp = 0x6f79,
        LoadSpellSet = 0x7113,
        Bandolier = 0x441c,
        PotionBelt = 0x5db5,
        DuelResponse = 0x1ebb,
        SaveOnZoneReq = 0x6eff,
        ReadBook = 0x2444,
        Dye = 0x3672,
        InterruptCast = 0x072f,
        AAAction = 0x50d0,
        LeadershipExpToggle = 0x34c5,
        LeadershipExpUpdate = 0x69d0,
        PurchaseLeadershipAA = 0x07b3,
        UpdateLeadershipAA = 0x6948,
        MarkNPC = 0x695c,
        MarkRaidNPC = 0x0d4b,
        ClearNPCMarks = 0x5033,
        ClearRaidNPCMarks = 0x5f55,
        DoGroupLeadershipAbility = 0x540b,
        GroupLeadershipAAUpdate = 0x0c33,
        DelegateAbility = 0x0322,
        SetGroupTarget = 0x521c,
        DuelResponse2 = 0x52b5,
        Charm = 0x7108,
        Stun = 0x2a6d,
        SendFindableNPCs = 0x5360,
        FindPersonRequest = 0x3168,
        FindPersonReply = 0x1ac8,
        Sound = 0x303e,
        PetBuffWindow = 0x2dd3,
        LevelAppearance = 0x6dc3,
        Translocate = 0x2042,
        Sacrifice = 0x5805,
        PopupResponse = 0x2caf,
        OnLevelMessage = 0x1154,
        AugmentInfo = 0x3683,
        Petition = 0x31d1,
        SomeItemPacketMaybe = 0x54e8,
        PVPStats = 0x6a37,
        PVPLeaderBoardRequest = 0x24cb,
        PVPLeaderBoardReply = 0x6ac2,
        PVPLeaderBoardDetailsRequest = 0x2a99,
        PVPLeaderBoardDetailsReply = 0x5156,
        RestState = 0x292f,
        RespawnWindow = 0x268c,
        DisciplineTimer = 0x684c,
        LDoNButton = 0x41b5,
        SetStartCity = 0x7bf6,
        VoiceMacroIn = 0x31b1,
        VoiceMacroOut = 0x7880,
        ItemViewUnknown = 0x21c7,
        VetRewardsAvaliable = 0x4e4e,
        VetClaimRequest = 0x771f,
        VetClaimReply = 0x2f95,
        CrystalCountUpdate = 0x2d0e,
        CrystalReclaim = 0x4d4b,
        CrystalCreate = 0x6c80,
        DisciplineUpdate = 0x7b87,
        CameraEffect = 0x0d96,
        SpellEffect = 0x7309,
        AltCurrency = 0x25e4,
        AltCurrencyMerchantRequest = 0x440d,
        AltCurrencyMerchantReply = 0x3c37,
        AltCurrencyPurchase = 0x5270,
        AltCurrencySell = 0x7a21,
        AltCurrencySellSelection = 0x26d9,
        AltCurrencyReclaim = 0x712c,
        ShroudProgress = 0x0296,
        RemoveNimbusEffect = 0x5272,
        Untargetable = 0x5ea1,
        IncreaseStats = 0x71eb,
        InspectMessageUpdate = 0x53a3,
        OpenInventory = 0x1003,
        OpenContainer = 0x3278,
        Marquee = 0x7dc9,
        DzQuit = 0x054e,
        DzListTimers = 0x3200,
        DzAddPlayer = 0x3ba3,
        DzRemovePlayer = 0xa682,
        DzSwapPlayer = 0x0d8d,
        DzMakeLeader = 0x1caa,
        DzPlayerList = 0x74ca,
        DzJoinExpeditionConfirm = 0x1772,
        DzJoinExpeditionReply = 0x3c13,
        DzExpeditionInfo = 0x128e,
        DzMemberStatus = 0x4661,
        DzLeaderStatus = 0x226f,
        DzExpeditionEndsWarning = 0x1879,
        DzExpeditionList = 0x3657,
        DzMemberList = 0x74e4,
        DzCompass = 0x35d3,
        DzChooseZone = 0x0d8a,
        SpawnPositionUpdate = 0x4656,
        ManaUpdate = 0x4b61,
        EnduranceUpdate = 0x02d6,
        MobManaUpdate = 0x2ac1,
        MobEnduranceUpdate = 0x6c5f,
        LootRequest = 0x2701,
        EndLootRequest = 0x6ad7,
        LootItem = 0x2b5a,
        LootComplete = 0x41a6,
        BazaarSearch = 0x4675,
        TraderDelItem = 0x63c8,
        BecomeTrader = 0x528f,
        TraderShop = 0x7598,
        Trader = 0x7092,
        TraderBuy = 0x053a,
        Barter = 0x4b49,
        TradeRequest = 0x47ae,
        TradeAcceptClick = 0x064a,
        TradeRequestAck = 0x606a,
        TradeCoins = 0x0149,
        FinishTrade = 0x3ff6,
        CancelTrade = 0x527e,
        TradeMoneyUpdate = 0x7452,
        MoneyUpdate = 0x2d1d,
        TradeBusy = 0x0c2d,
        FinishWindow = 0x3c27,
        FinishWindow2 = 0x2f5d,
        ItemVerifyRequest = 0x032a,
        ItemVerifyReply = 0x7866,
        ShopPlayerSell = 0x0b27,
        ShopRequest = 0x4194,
        ShopEnd = 0x3753,
        ShopEndConfirm = 0x7114,
        ShopPlayerBuy = 0x436a,
        ShopDelItem = 0x63c8,
        ClickObject = 0x5f0d,
        ClickObjectAction = 0x5dbc,
        ClearObject = 0x0b80,
        RecipeDetails = 0x49f4,
        RecipesFavorite = 0x1150,
        RecipesSearch = 0x55dd,
        RecipeReply = 0x0643,
        RecipeAutoCombine = 0x1564,
        TradeSkillCombine = 0x4212,
        OpenGuildTributeMaster = 0x6361,
        OpenTributeMaster = 0x2daa,
        SelectTribute = 0x38b0,
        TributeItem = 0x416b,
        TributeMoney = 0x0b89,
        TributeToggle = 0x45b3,
        TributePointUpdate = 0x7d05,
        LeaveAdventure = 0x2ab6,
        AdventureFinish = 0x624c,
        AdventureInfoRequest = 0x3a75,
        AdventureInfo = 0x3a28,
        AdventureRequest = 0x5a55,
        AdventureDetails = 0x5ed3,
        AdventureUpdate = 0x0dcd,
        AdventureMerchantRequest = 0x0989,
        AdventureMerchantResponse = 0x6ade,
        AdventureMerchantPurchase = 0x23fc,
        AdventureMerchantSell = 0x5363,
        AdventurePointsUpdate = 0x6b7f,
        AdventureStatsRequest = 0x7e45,
        AdventureStatsReply = 0x6a30,
        AdventureLeaderboardRequest = 0x7537,
        AdventureLeaderboardReply = 0x7c87,
        GroupDisband = 0x47e7,
        GroupInvite = 0x5d32,
        GroupFollow = 0x321a,
        GroupUpdate = 0x21be,
        GroupUpdateB = 0x7351,
        GroupCancelInvite = 0x5251,
        GroupAcknowledge = 0x3e22,
        GroupDelete = 0x58e6,
        CancelInvite = 0x5251,
        GroupFollow2 = 0x2736,
        GroupInvite2 = 0x548c,
        GroupDisbandYou = 0xc56c,
        GroupDisbandOther = 0x162d,
        GroupLeaderChange = 0x7545,
        GroupRoles = 0x6b67,
        GroupMakeLeader = 0x6087,
        GroupMentor = 0x1224,
        InspectBuffs = 0x66bf,
        LFGCommand = 0x3288,
        LFGGetMatchesRequest = 0x5613,
        LFGGetMatchesResponse = 0x7d90,
        LFPGetMatchesRequest = 0x0479,
        LFPGetMatchesResponse = 0x16f5,
        LFPCommand = 0x710e,
        RaidInvite = 0x3b52,
        RaidUpdate = 0x32c6,
        Taunt = 0x1418,
        CombatAbility = 0x24c5,
        SenseTraps = 0x1e04,
        PickPocket = 0x25f0,
        Disarm = 0x6def,
        Sneak = 0x03e7,
        Fishing = 0x7093,
        InstillDoubt = 0x2d41,
        FeignDeath = 0x3f49,
        Mend = 0x221a,
        LDoNOpen = 0x6129,
        TaskActivityComplete = 0x4df0,
        TaskMemberList = 0x34ed,
        OpenNewTasksWindow = 0x4dd5,
        AvaliableTask = 0x2136,
        AcceptNewTask = 0x5832,
        TaskHistoryRequest = 0x29d7,
        TaskHistoryReply = 0x3d2a,
        CancelTask = 0x726b,
        Shroud = 0x6d1f,
        ShroudRemove = 0x17f6,
        ShroudUnknown1 = 0x169a,
        ShroudUnknown2 = 0x4292,
        ClearAA = 0x3bef,
        ClearLeadershipAbilities = 0x6e58,
        ShroudSelectionWindow = 0x4d79,
        ShroudRequestStats = 0x28ce,
        ShroudRespondStats = 0x33f2,
        ShroudSelect = 0x194f,
        NewTitlesAvailable = 0x4399,
        RequestTitles = 0x7327,
        SendTitleList = 0x158f,
        SetTitle = 0x698a,
        SetTitleReply = 0x4d3e,
        MercenaryDataRequest = 0x4717,
        MercenaryDataResponse = 0x1715,
        MercenaryHire = 0x0bfd,
        MercenaryAssign = 0x6188,
        MercenaryTimer = 0x116d,
        MercenaryUnknown1 = 0x28c7,
        MercenaryDataUpdate = 0x0786,
        MercenaryCommand = 0x27bf,
        MercenarySuspendRequest = 0x05f1,
        MercenarySuspendResponse = 0x57f2,
        MercenaryUnsuspendResponse = 0x3015,
        MercenaryDataUpdateRequest = 0x390c,
        MercenaryDismiss = 0x0bd0,
        MercenaryTimerRequest = 0x0924,
        PlayMP3 = 0x82d7,
        ItemRecastDelay = 0x15c4,
        COUNT
    };

    static const OpCodeTranslation toCanonical[] = {
        { 0x0ff4, CanonicalOp::SendLoginInfo },
        { 0x701f, CanonicalOp::ApproveWorld },
        { 0x4762, CanonicalOp::LogServer },
        { 0x0f14, CanonicalOp::SendCharInfo },
        { 0x7519, CanonicalOp::ExpansionInfo },
        { 0x5b0b, CanonicalOp::GuildsList },
        { 0x1c20, CanonicalOp::EnterWorld },
        { 0x7c94, CanonicalOp::PostEnterWorld },
        { 0x5bad, CanonicalOp::SendSpellChecksum },
        { 0x5d24, CanonicalOp::SendSkillCapsChecksum },
        { 0x0254, CanonicalOp::DeleteCharacter },
        { 0x4463, CanonicalOp::CharacterCreateRequest },
        { 0x1513, CanonicalOp::CharacterCreate },
        { 0x3604, CanonicalOp::RandomNameGenerator },
        { 0x413f, CanonicalOp::ApproveName },
        { 0x192e, CanonicalOp::MOTD },
        { 0x7f2b, CanonicalOp::SetChatServer },
        { 0x11f3, CanonicalOp::SetChatServer2 },
        { 0x5da4, CanonicalOp::ZoneServerInfo },
        { 0x37db, CanonicalOp::WorldComplete },
        { 0x2c4c, CanonicalOp::WorldUnknown001 },
        { 0x10b5, CanonicalOp::FloatListThing },
        { 0x7930, CanonicalOp::ZoneUnavail },
        { 0x1a84, CanonicalOp::WorldClientReady },
        { 0x3594, CanonicalOp::AckPacket },
        { 0x5a6b, CanonicalOp::ZoneEntry },
        { 0x43ac, CanonicalOp::ReqNewZone },
        { 0x5ca5, CanonicalOp::NewZone },
        { 0x72f8, CanonicalOp::ZoneSpawns },
        { 0x6022, CanonicalOp::PlayerProfile },
        { 0x6015, CanonicalOp::TimeOfDay },
        { 0x6a99, CanonicalOp::LevelUpdate },
        { 0x3e50, CanonicalOp::Stamina },
        { 0x4885, CanonicalOp::RequestClientZoneChange },
        { 0x051b, CanonicalOp::ZoneChange },
        { 0x10b7, CanonicalOp::SpawnAppearance },
        { 0x399b, CanonicalOp::TributeUpdate },
        { 0x4423, CanonicalOp::TributeTimer },
        { 0x7b77, CanonicalOp::TaskDescription },
        { 0x0525, CanonicalOp::TaskActivity },
        { 0x5412, CanonicalOp::CompletedTasks },
        { 0x2641, CanonicalOp::Weather },
        { 0x322f, CanonicalOp::SendAATable },
        { 0x466c, CanonicalOp::UpdateAA },
        { 0x0142, CanonicalOp::RespondAA },
        { 0x1436, CanonicalOp::ReqClientSpawn },
        { 0x102f, CanonicalOp::SpawnDoor },
        { 0x33e5, CanonicalOp::GroundSpawn },
        { 0x5821, CanonicalOp::SendZonepoints },
        { 0x57a3, CanonicalOp::SendAAStats },
        { 0x7b73, CanonicalOp::WorldObjectsSent },
        { 0x0baa, CanonicalOp::BlockedBuffs },
        { 0x064d, CanonicalOp::RemoveBlockedBuffs },
        { 0x4027, CanonicalOp::ClearBlockedBuffs },
        { 0x69cd, CanonicalOp::SendExpZonein },
        { 0x4786, CanonicalOp::SendTributes },
        { 0x4cc6, CanonicalOp::TributeInfo },
        { 0x26c4, CanonicalOp::SendGuildTributes },
        { 0x3088, CanonicalOp::AAExpUpdate },
        { 0x0e98, CanonicalOp::ExpUpdate },
        { 0x538f, CanonicalOp::HPUpdate },
        { 0x50c2, CanonicalOp::ManaChange },
        { 0x2d74, CanonicalOp::TGB },
        { 0x074f, CanonicalOp::SpecialMesg },
        { 0x51bc, CanonicalOp::GuildMemberList },
        { 0xd677, CanonicalOp::GuildMOTD },
        { 0x709d, CanonicalOp::CharInventory },
        { 0x231f, CanonicalOp::WearChange },
        { 0x7062, CanonicalOp::ClientUpdate },
        { 0x6759, CanonicalOp::ClientReady },
        { 0x7312, CanonicalOp::SetServerFilter },
        { 0x189e, CanonicalOp::GetGuildMOTD },
        { 0x7a16, CanonicalOp::GetGuildMOTDReply },
        { 0x41c0, CanonicalOp::GuildMemberUpdate },
        { 0x4843, CanonicalOp::GuildInvite },
        { 0x2b9d, CanonicalOp::GuildRemove },
        { 0x3f21, CanonicalOp::GuildPeace },
        { 0x481f, CanonicalOp::SetGuildMOTD },
        { 0x5b0b, CanonicalOp::GuildList },
        { 0x7bfb, CanonicalOp::GuildWar },
        { 0x1055, CanonicalOp::GuildLeader },
        { 0x75d0, CanonicalOp::GuildDelete },
        { 0x5f25, CanonicalOp::GuildInviteAccept },
        { 0x15b2, CanonicalOp::GuildDemote },
        { 0x2dbd, CanonicalOp::GuildPublicNote },
        { 0x11bc, CanonicalOp::GuildManageBanker },
        { 0x0fce, CanonicalOp::GuildBank },
        { 0x4ffe, CanonicalOp::SetGuildRank },
        { 0x5422, CanonicalOp::GuildUpdateURLAndChannel },
        { 0x5479, CanonicalOp::GuildStatus },
        { 0x40e8, CanonicalOp::LFGuild },
        { 0x6989, CanonicalOp::GMServers },
        { 0x56e7, CanonicalOp::GMBecomeNPC },
        { 0x4578, CanonicalOp::GMZoneRequest },
        { 0x1912, CanonicalOp::GMZoneRequest2 },
        { 0x0402, CanonicalOp::GMGoto },
        { 0x7872, CanonicalOp::GMSearchCorpse },
        { 0x34a1, CanonicalOp::GMHideMe },
        { 0x0dda, CanonicalOp::GMDelCorpse },
        { 0x72fa, CanonicalOp::GMApproval },
        { 0x7566, CanonicalOp::GMToggle },
        { 0x596d, CanonicalOp::GMSummon },
        { 0x3e7c, CanonicalOp::GMEmoteZone },
        { 0x5298, CanonicalOp::GMEmoteWorld },
        { 0x6e27, CanonicalOp::GMFind },
        { 0x799c, CanonicalOp::GMKick },
        { 0x6685, CanonicalOp::GMKill },
        { 0x565d, CanonicalOp::GMNameChange },
        { 0x3563, CanonicalOp::GMLastName },
        { 0x4938, CanonicalOp::InspectAnswer },
        { 0x7e4d, CanonicalOp::Action2 },
        { 0x0d5a, CanonicalOp::BeginCast },
        { 0x569a, CanonicalOp::ColoredText },
        { 0x6e47, CanonicalOp::ConsentResponse },
        { 0x8543, CanonicalOp::MemorizeSpell },
        { 0x3fd2, CanonicalOp::SwapSpell },
        { 0x3582, CanonicalOp::CastSpell },
        { 0x6024, CanonicalOp::Consider },
        { 0x1318, CanonicalOp::FormattedMessage },
        { 0x5448, CanonicalOp::SimpleMessage },
        { 0x7ea8, CanonicalOp::Buff },
        { 0x48f9, CanonicalOp::Illusion },
        { 0x6546, CanonicalOp::MoneyOnCorpse },
        { 0x6cdc, CanonicalOp::RandomReply },
        { 0x7ce7, CanonicalOp::DenyResponse },
        { 0x7f01, CanonicalOp::SkillUpdate },
        { 0x7ae1, CanonicalOp::GMTrainSkillConfirm },
        { 0x777c, CanonicalOp::RandomReq },
        { 0x1b85, CanonicalOp::Death },
        { 0x7b64, CanonicalOp::GMTraining },
        { 0x3c02, CanonicalOp::GMEndTraining },
        { 0x7686, CanonicalOp::GMTrainSkill },
        { 0x47d3, CanonicalOp::Animation },
        { 0x6d37, CanonicalOp::Begging },
        { 0x6bb9, CanonicalOp::Consent },
        { 0x01e3, CanonicalOp::ConsentDeny },
        { 0x1bd4, CanonicalOp::AutoFire },
        { 0x3ad6, CanonicalOp::PetCommands },
        { 0x0736, CanonicalOp::DeleteSpell },
        { 0x7547, CanonicalOp::Surname },
        { 0x2edd, CanonicalOp::ClearSurname },
        { 0x5658, CanonicalOp::FaceChange },
        { 0x3887, CanonicalOp::SenseHeading },
        { 0x2c27, CanonicalOp::Action },
        { 0x37a7, CanonicalOp::ConsiderCorpse },
        { 0x1842, CanonicalOp::HideCorpse },
        { 0x5a6f, CanonicalOp::CorpseDrag },
        { 0x5a01, CanonicalOp::CorpseDrop },
        { 0x002b, CanonicalOp::Bug },
        { 0x0d1d, CanonicalOp::Feedback },
        { 0x6884, CanonicalOp::Report },
        { 0x7e4d, CanonicalOp::Damage },
        { 0x2e79, CanonicalOp::ChannelMessage },
        { 0x2b59, CanonicalOp::Assist },
        { 0x5af6, CanonicalOp::AssistGroup },
        { 0x1fcd, CanonicalOp::MoveCoin },
        { 0x1d3f, CanonicalOp::ZonePlayerToBind },
        { 0x0a18, CanonicalOp::KeyRing },
        { 0x177a, CanonicalOp::WhoAllRequest },
        { 0x31f3, CanonicalOp::WhoAllResponse },
        { 0x6a90, CanonicalOp::FriendsWho },
        { 0x3d00, CanonicalOp::ConfirmDelete },
        { 0x66e0, CanonicalOp::Logout },
        { 0x4b7b, CanonicalOp::Rewind },
        { 0x17f7, CanonicalOp::TargetCommand },
        { 0x4892, CanonicalOp::InspectRequest },
        { 0x1d22, CanonicalOp::Hide },
        { 0x6c16, CanonicalOp::Jump },
        { 0x3eec, CanonicalOp::Camp },
        { 0x7434, CanonicalOp::Emote },
        { 0x07fb, CanonicalOp::SetRunMode },
        { 0x21e9, CanonicalOp::BankerChange },
        { 0x7bbb, CanonicalOp::TargetMouse },
        { 0x47ea, CanonicalOp::MobHealth },
        { 0x2d25, CanonicalOp::InitialMobHealth },
        { 0x3ec7, CanonicalOp::TargetHoTT },
        { 0x3df8, CanonicalOp::TargetBuffs },
        { 0x6f9d, CanonicalOp::BuffRemoveRequest },
        { 0x3164, CanonicalOp::DeleteSpawn },
        { 0x3d86, CanonicalOp::AutoAttack },
        { 0x4ca1, CanonicalOp::AutoAttack2 },
        { 0x7ce4, CanonicalOp::Consume },
        { 0x7f56, CanonicalOp::MoveItem },
        { 0x36f8, CanonicalOp::DeleteItem },
        { 0x1df9, CanonicalOp::DeleteCharge },
        { 0x34f8, CanonicalOp::ItemPacket },
        { 0x2bad, CanonicalOp::ItemLinkResponse },
        { 0x3c66, CanonicalOp::ItemLinkClick },
        { 0x5c29, CanonicalOp::NewSpawn },
        { 0x4817, CanonicalOp::Track },
        { 0x7337, CanonicalOp::TrackTarget },
        { 0x7b56, CanonicalOp::TrackUnknown },
        { 0x1516, CanonicalOp::ClickDoor },
        { 0x6e97, CanonicalOp::MoveDoor },
        { 0x1a58, CanonicalOp::RemoveAllDoors },
        { 0x5ac4, CanonicalOp::EnvDamage },
        { 0x5cd3, CanonicalOp::BoardBoat },
        { 0x7b05, CanonicalOp::Forage },
        { 0x7554, CanonicalOp::LeaveBoat },
        { 0x5bd9, CanonicalOp::ControlBoat },
        { 0x6ad2, CanonicalOp::SafeFallSuccess },
        { 0x42d0, CanonicalOp::RezzComplete },
        { 0x0976, CanonicalOp::RezzRequest },
        { 0x6e1c, CanonicalOp::RezzAnswer },
        { 0x2f6a, CanonicalOp::Shielding },
        { 0x79e0, CanonicalOp::RequestDuel },
        { 0x0a1d, CanonicalOp::MobRename },
        { 0x0370, CanonicalOp::AugmentItem },
        { 0x719e, CanonicalOp::WeaponEquip1 },
        { 0x7b6e, CanonicalOp::PlayerStateAdd },
        { 0x19a8, CanonicalOp::PlayerStateRemove },
        { 0x405b, CanonicalOp::ApplyPoison },
        { 0x5c85, CanonicalOp::Save },
        { 0x5fc7, CanonicalOp::TestBuff },
        { 0x5ea1, CanonicalOp::DestructableRelated },
        { 0x1b26, CanonicalOp::CustomTitles },
        { 0x53f9, CanonicalOp::Split },
        { 0x6f79, CanonicalOp::YellForHelp },
        { 0x7113, CanonicalOp::LoadSpellSet },
        { 0x441c, CanonicalOp::Bandolier },
        { 0x5db5, CanonicalOp::PotionBelt },
        { 0x1ebb, CanonicalOp::DuelResponse },
        { 0x6eff, CanonicalOp::SaveOnZoneReq },
        { 0x2444, CanonicalOp::ReadBook },
        { 0x3672, CanonicalOp::Dye },
        { 0x072f, CanonicalOp::InterruptCast },
        { 0x50d0, CanonicalOp::AAAction },
        { 0x34c5, CanonicalOp::LeadershipExpToggle },
        { 0x69d0, CanonicalOp::LeadershipExpUpdate },
        { 0x07b3, CanonicalOp::PurchaseLeadershipAA },
        { 0x6948, CanonicalOp::UpdateLeadershipAA },
        { 0x695c, CanonicalOp::MarkNPC },
        { 0x0d4b, CanonicalOp::MarkRaidNPC },
        { 0x5033, CanonicalOp::ClearNPCMarks },
        { 0x5f55, CanonicalOp::ClearRaidNPCMarks },
        { 0x540b, CanonicalOp::DoGroupLeadershipAbility },
        { 0x0c33, CanonicalOp::GroupLeadershipAAUpdate },
        { 0x0322, CanonicalOp::DelegateAbility },
        { 0x521c, CanonicalOp::SetGroupTarget },
        { 0x52b5, CanonicalOp::DuelResponse2 },
        { 0x7108, CanonicalOp::Charm },
        { 0x2a6d, CanonicalOp::Stun },
        { 0x5360, CanonicalOp::SendFindableNPCs },
        { 0x3168, CanonicalOp::FindPersonRequest },
        { 0x1ac8, CanonicalOp::FindPersonReply },
        { 0x303e, CanonicalOp::Sound },
        { 0x2dd3, CanonicalOp::PetBuffWindow },
        { 0x6dc3, CanonicalOp::LevelAppearance },
        { 0x2042, CanonicalOp::Translocate },
        { 0x5805, CanonicalOp::Sacrifice },
        { 0x2caf, CanonicalOp::PopupResponse },
        { 0x1154, CanonicalOp::OnLevelMessage },
        { 0x3683, CanonicalOp::AugmentInfo },
        { 0x31d1, CanonicalOp::Petition },
        { 0x54e8, CanonicalOp::SomeItemPacketMaybe },
        { 0x6a37, CanonicalOp::PVPStats },
        { 0x24cb, CanonicalOp::PVPLeaderBoardRequest },
        { 0x6ac2, CanonicalOp::PVPLeaderBoardReply },
        { 0x2a99, CanonicalOp::PVPLeaderBoardDetailsRequest },
        { 0x5156, CanonicalOp::PVPLeaderBoardDetailsReply },
        { 0x292f, CanonicalOp::RestState },
        { 0x268c, CanonicalOp::RespawnWindow },
        { 0x684c, CanonicalOp::DisciplineTimer },
        { 0x41b5, CanonicalOp::LDoNButton },
        { 0x7bf6, CanonicalOp::SetStartCity },
        { 0x31b1, CanonicalOp::VoiceMacroIn },
        { 0x7880, CanonicalOp::VoiceMacroOut },
        { 0x21c7, CanonicalOp::ItemViewUnknown },
        { 0x4e4e, CanonicalOp::VetRewardsAvaliable },
        { 0x771f, CanonicalOp::VetClaimRequest },
        { 0x2f95, CanonicalOp::VetClaimReply },
        { 0x2d0e, CanonicalOp::CrystalCountUpdate },
        { 0x4d4b, CanonicalOp::CrystalReclaim },
        { 0x6c80, CanonicalOp::CrystalCreate },
        { 0x7b87, CanonicalOp::DisciplineUpdate },
        { 0x0d96, CanonicalOp::CameraEffect },
        { 0x7309, CanonicalOp::SpellEffect },
        { 0x25e4, CanonicalOp::AltCurrency },
        { 0x440d, CanonicalOp::AltCurrencyMerchantRequest },
        { 0x3c37, CanonicalOp::AltCurrencyMerchantReply },
        { 0x5270, CanonicalOp::AltCurrencyPurchase },
        { 0x7a21, CanonicalOp::AltCurrencySell },
        { 0x26d9, CanonicalOp::AltCurrencySellSelection },
        { 0x712c, CanonicalOp::AltCurrencyReclaim },
        { 0x0296, CanonicalOp::ShroudProgress },
        { 0x5272, CanonicalOp::RemoveNimbusEffect },
        { 0x5ea1, CanonicalOp::Untargetable },
        { 0x71eb, CanonicalOp::IncreaseStats },
        { 0x53a3, CanonicalOp::InspectMessageUpdate },
        { 0x1003, CanonicalOp::OpenInventory },
        { 0x3278, CanonicalOp::OpenContainer },
        { 0x7dc9, CanonicalOp::Marquee },
        { 0x054e, CanonicalOp::DzQuit },
        { 0x3200, CanonicalOp::DzListTimers },
        { 0x3ba3, CanonicalOp::DzAddPlayer },
        { 0xa682, CanonicalOp::DzRemovePlayer },
        { 0x0d8d, CanonicalOp::DzSwapPlayer },
        { 0x1caa, CanonicalOp::DzMakeLeader },
        { 0x74ca, CanonicalOp::DzPlayerList },
        { 0x1772, CanonicalOp::DzJoinExpeditionConfirm },
        { 0x3c13, CanonicalOp::DzJoinExpeditionReply },
        { 0x128e, CanonicalOp::DzExpeditionInfo },
        { 0x4661, CanonicalOp::DzMemberStatus },
        { 0x226f, CanonicalOp::DzLeaderStatus },
        { 0x1879, CanonicalOp::DzExpeditionEndsWarning },
        { 0x3657, CanonicalOp::DzExpeditionList },
        { 0x74e4, CanonicalOp::DzMemberList },
        { 0x35d3, CanonicalOp::DzCompass },
        { 0x0d8a, CanonicalOp::DzChooseZone },
        { 0x4656, CanonicalOp::SpawnPositionUpdate },
        { 0x4b61, CanonicalOp::ManaUpdate },
        { 0x02d6, CanonicalOp::EnduranceUpdate },
        { 0x2ac1, CanonicalOp::MobManaUpdate },
        { 0x6c5f, CanonicalOp::MobEnduranceUpdate },
        { 0x2701, CanonicalOp::LootRequest },
        { 0x6ad7, CanonicalOp::EndLootRequest },
        { 0x2b5a, CanonicalOp::LootItem },
        { 0x41a6, CanonicalOp::LootComplete },
        { 0x4675, CanonicalOp::BazaarSearch },
        { 0x63c8, CanonicalOp::TraderDelItem },
        { 0x528f, CanonicalOp::BecomeTrader },
        { 0x7598, CanonicalOp::TraderShop },
        { 0x7092, CanonicalOp::Trader },
        { 0x053a, CanonicalOp::TraderBuy },
        { 0x4b49, CanonicalOp::Barter },
        { 0x47ae, CanonicalOp::TradeRequest },
        { 0x064a, CanonicalOp::TradeAcceptClick },
        { 0x606a, CanonicalOp::TradeRequestAck },
        { 0x0149, CanonicalOp::TradeCoins },
        { 0x3ff6, CanonicalOp::FinishTrade },
        { 0x527e, CanonicalOp::CancelTrade },
        { 0x7452, CanonicalOp::TradeMoneyUpdate },
        { 0x2d1d, CanonicalOp::MoneyUpdate },
        { 0x0c2d, CanonicalOp::TradeBusy },
        { 0x3c27, CanonicalOp::FinishWindow },
        { 0x2f5d, CanonicalOp::FinishWindow2 },
        { 0x032a, CanonicalOp::ItemVerifyRequest },
        { 0x7866, CanonicalOp::ItemVerifyReply },
        { 0x0b27, CanonicalOp::ShopPlayerSell },
        { 0x4194, CanonicalOp::ShopRequest },
        { 0x3753, CanonicalOp::ShopEnd },
        { 0x7114, CanonicalOp::ShopEndConfirm },
        { 0x436a, CanonicalOp::ShopPlayerBuy },
        { 0x63c8, CanonicalOp::ShopDelItem },
        { 0x5f0d, CanonicalOp::ClickObject },
        { 0x5dbc, CanonicalOp::ClickObjectAction },
        { 0x0b80, CanonicalOp::ClearObject },
        { 0x49f4, CanonicalOp::RecipeDetails },
        { 0x1150, CanonicalOp::RecipesFavorite },
        { 0x55dd, CanonicalOp::RecipesSearch },
        { 0x0643, CanonicalOp::RecipeReply },
        { 0x1564, CanonicalOp::RecipeAutoCombine },
        { 0x4212, CanonicalOp::TradeSkillCombine },
        { 0x6361, CanonicalOp::OpenGuildTributeMaster },
        { 0x2daa, CanonicalOp::OpenTributeMaster },
        { 0x38b0, CanonicalOp::SelectTribute },
        { 0x416b, CanonicalOp::TributeItem },
        { 0x0b89, CanonicalOp::TributeMoney },
        { 0x45b3, CanonicalOp::TributeToggle },
        { 0x7d05, CanonicalOp::TributePointUpdate },
        { 0x2ab6, CanonicalOp::LeaveAdventure },
        { 0x624c, CanonicalOp::AdventureFinish },
        { 0x3a75, CanonicalOp::AdventureInfoRequest },
        { 0x3a28, CanonicalOp::AdventureInfo },
        { 0x5a55, CanonicalOp::AdventureRequest },
        { 0x5ed3, CanonicalOp::AdventureDetails },
        { 0x0dcd, CanonicalOp::AdventureUpdate },
        { 0x0989, CanonicalOp::AdventureMerchantRequest },
        { 0x6ade, CanonicalOp::AdventureMerchantResponse },
        { 0x23fc, CanonicalOp::AdventureMerchantPurchase },
        { 0x5363, CanonicalOp::AdventureMerchantSell },
        { 0x6b7f, CanonicalOp::AdventurePointsUpdate },
        { 0x7e45, CanonicalOp::AdventureStatsRequest },
        { 0x6a30, CanonicalOp::AdventureStatsReply },
        { 0x7537, CanonicalOp::AdventureLeaderboardRequest },
        { 0x7c87, CanonicalOp::AdventureLeaderboardReply },
        { 0x47e7, CanonicalOp::GroupDisband },
        { 0x5d32, CanonicalOp::GroupInvite },
        { 0x321a, CanonicalOp::GroupFollow },
        { 0x21be, CanonicalOp::GroupUpdate },
        { 0x7351, CanonicalOp::GroupUpdateB },
        { 0x5251, CanonicalOp::GroupCancelInvite },
        { 0x3e22, CanonicalOp::GroupAcknowledge },
        { 0x58e6, CanonicalOp::GroupDelete },
        { 0x5251, CanonicalOp::CancelInvite },
        { 0x2736, CanonicalOp::GroupFollow2 },
        { 0x548c, CanonicalOp::GroupInvite2 },
        { 0xc56c, CanonicalOp::GroupDisbandYou },
        { 0x162d, CanonicalOp::GroupDisbandOther },
        { 0x7545, CanonicalOp::GroupLeaderChange },
        { 0x6b67, CanonicalOp::GroupRoles },
        { 0x6087, CanonicalOp::GroupMakeLeader },
        { 0x1224, CanonicalOp::GroupMentor },
        { 0x66bf, CanonicalOp::InspectBuffs },
        { 0x3288, CanonicalOp::LFGCommand },
        { 0x5613, CanonicalOp::LFGGetMatchesRequest },
        { 0x7d90, CanonicalOp::LFGGetMatchesResponse },
        { 0x0479, CanonicalOp::LFPGetMatchesRequest },
        { 0x16f5, CanonicalOp::LFPGetMatchesResponse },
        { 0x710e, CanonicalOp::LFPCommand },
        { 0x3b52, CanonicalOp::RaidInvite },
        { 0x32c6, CanonicalOp::RaidUpdate },
        { 0x1418, CanonicalOp::Taunt },
        { 0x24c5, CanonicalOp::CombatAbility },
        { 0x1e04, CanonicalOp::SenseTraps },
        { 0x25f0, CanonicalOp::PickPocket },
        { 0x6def, CanonicalOp::Disarm },
        { 0x03e7, CanonicalOp::Sneak },
        { 0x7093, CanonicalOp::Fishing },
        { 0x2d41, CanonicalOp::InstillDoubt },
        { 0x3f49, CanonicalOp::FeignDeath },
        { 0x221a, CanonicalOp::Mend },
        { 0x6129, CanonicalOp::LDoNOpen },
        { 0x4df0, CanonicalOp::TaskActivityComplete },
        { 0x34ed, CanonicalOp::TaskMemberList },
        { 0x4dd5, CanonicalOp::OpenNewTasksWindow },
        { 0x2136, CanonicalOp::AvaliableTask },
        { 0x5832, CanonicalOp::AcceptNewTask },
        { 0x29d7, CanonicalOp::TaskHistoryRequest },
        { 0x3d2a, CanonicalOp::TaskHistoryReply },
        { 0x726b, CanonicalOp::CancelTask },
        { 0x6d1f, CanonicalOp::Shroud },
        { 0x17f6, CanonicalOp::ShroudRemove },
        { 0x169a, CanonicalOp::ShroudUnknown1 },
        { 0x4292, CanonicalOp::ShroudUnknown2 },
        { 0x3bef, CanonicalOp::ClearAA },
        { 0x6e58, CanonicalOp::ClearLeadershipAbilities },
        { 0x4d79, CanonicalOp::ShroudSelectionWindow },
        { 0x28ce, CanonicalOp::ShroudRequestStats },
        { 0x33f2, CanonicalOp::ShroudRespondStats },
        { 0x194f, CanonicalOp::ShroudSelect },
        { 0x4399, CanonicalOp::NewTitlesAvailable },
        { 0x7327, CanonicalOp::RequestTitles },
        { 0x158f, CanonicalOp::SendTitleList },
        { 0x698a, CanonicalOp::SetTitle },
        { 0x4d3e, CanonicalOp::SetTitleReply },
        { 0x4717, CanonicalOp::MercenaryDataRequest },
        { 0x1715, CanonicalOp::MercenaryDataResponse },
        { 0x0bfd, CanonicalOp::MercenaryHire },
        { 0x6188, CanonicalOp::MercenaryAssign },
        { 0x116d, CanonicalOp::MercenaryTimer },
        { 0x28c7, CanonicalOp::MercenaryUnknown1 },
        { 0x0786, CanonicalOp::MercenaryDataUpdate },
        { 0x27bf, CanonicalOp::MercenaryCommand },
        { 0x05f1, CanonicalOp::MercenarySuspendRequest },
        { 0x57f2, CanonicalOp::MercenarySuspendResponse },
        { 0x3015, CanonicalOp::MercenaryUnsuspendResponse },
        { 0x390c, CanonicalOp::MercenaryDataUpdateRequest },
        { 0x0bd0, CanonicalOp::MercenaryDismiss },
        { 0x0924, CanonicalOp::MercenaryTimerRequest },
        { 0x82d7, CanonicalOp::PlayMP3 },
        { 0x15c4, CanonicalOp::ItemRecastDelay }
    };
}

#endif//_EQP_OPCODES_SOD_HPP_
